suppressMessages({library(data.table)})
j <- fread("REI_Jorstad_2023.csv", data.table=F)
a <- fread("REI_Average.csv", data.table=F)
g <- fread("REI_Gabitto_2024.csv", data.table=F)
l <- fread("REI_Liu_2025.csv", data.table=F)
m <- fread("REI_Morabito_2021.csv", data.table=F)
cat("dims jorstad:", dim(j), "\n")
cat("colnames:\n"); print(colnames(j))
cat("\n-- Module 354 (figure's module) Jorstad, first 6 cols:\n")
print(j[354, 1:6])
cat("\n-- Average check at Module 354, L2/3 IT:\n")
vals <- c(j[354,"L2/3 IT"], g[354,"L2/3 IT"], l[354,"L2/3 IT"], m[354,"L2/3 IT"])
cat("4 datasets:", vals, "\n")
cat("mean(na.rm):", mean(vals, na.rm=T), " table avg:", a[354,"L2/3 IT"], "\n")
cat("\n-- NA pattern (Liu lacks VLMC): Liu VLMC range:\n")
print(summary(l[["VLMC"]]))
cat("\n-- Average tab: any all-NA cells become NA. Count NA in avg body:", sum(is.na(a[,-1])), "\n")
