# v5
# - MTG analog of fig1_v3: identical structure, but uses the MTG DE data instead
#   of DFC. Loads the per-region gene-matched MTG DE objects produced by
#   full_DE_pipeline_optimized_v2.4.R (DE_v2.4/, *_MTG_*_matchedGenes.qs) instead
#   of generating DESeq2 inline and reading the old, un-matched edgeR objects.

library(qs)
library(data.table)
library(gt)
library(gtExtras)
library(ComplexHeatmap)
library(tidyverse)
library(UpSetR)
library(showtext)
showtext_auto()

# Rplots.pdf guard: grid::grid.grabExpr() (used for the Panel C UpSet capture) calls dev.set(),
# which auto-opens the default device. Under Rscript that default is pdf, leaving a stray
# Rplots.pdf in the working dir. Route any auto-opened device to the null pdf so no file is
# written. Explicit pdf()/svglite()/cairo_pdf()/ggsave() calls are unaffected.
options(device = function(...) grDevices::pdf(NULL))

version <- "v5"
# Set save dir (same folder as this script)
save_dir <- file.path(file.path(Sys.getenv("REPO_DIR", "/home/gugene/code/git/kang-oldham-2026"), "figures/fig_s2"), version)
if(!dir.exists(save_dir)){dir.create(save_dir, recursive = T)}
 
##############
# Load data (subclass)
##############


# Cell-type list (subclass), taken from the Jorstad MTG pseudobulk annotation.
# (DE objects are loaded precomputed below, so the expression matrices and
#  cell_anno_pb that earlier versions built here are no longer needed.)
cts <- fread(file.path(Sys.getenv("DATA_OTHER_DIR", "/home/gugene/data_other"), "lein_allRegions_pseudobulk_by_donor_all_genes/Lein_2023_cell_annotations_by_donor_subclass_sum_MTG.csv"), data.table = F)$Cell_Type |>
  factor() |>
  unique()
cts_upper <- as.character(cts)
cts_upper[c(13, 14, 18:24)] <- toupper(cts_upper[c(13, 14, 18:24)])

# Load DE objects (MTG) generated by full_DE_pipeline_optimized_v2.4.R
edger <- list(
  "jorstad" = qread(file.path(Sys.getenv("REPO_DIR", "/home/gugene/code/git/kang-oldham-2026"), "figures/fig_1/DE_v2.4/edgeR/jorstad/edgeR_jorstad_MTG_subclass_matchedGenes.qs")),
  "sea" = qread(file.path(Sys.getenv("REPO_DIR", "/home/gugene/code/git/kang-oldham-2026"), "figures/fig_1/DE_v2.4/edgeR/seaad/edgeR_seaad_MTG_subclass_matchedGenes.qs"))
)
# Make ct names match and same order
recode_map <- c("Astrocyte" = "Astro", "Endothelial" = "Endo", "Microglia-PVM" = "Micro/PVM", "Oligodendrocyte" = "Oligo")
hit <- names(edger[[2]]) %in% names(recode_map)
names(edger[[2]])[hit] <- recode_map[names(edger[[2]])[hit]]
# Sync the seaad internal celltype column to its recoded list names
edger[[2]] <- mapply(\(x, y){
  out <- x
  out$celltype <- y
  return(out)
}, edger[[2]], names(edger[[2]]), SIMPLIFY = F)
# Reorder BOTH datasets to canonical cts order so any positional ([[ind]]) indexing downstream is correct
edger <- lapply(edger, \(d) d[match(as.character(cts), names(d))])

reslist <- list(
  "jorstad" = qread(file = file.path(Sys.getenv("REPO_DIR", "/home/gugene/code/git/kang-oldham-2026"), "figures/fig_1/DE_v2.4/DESeq2/jorstad/DESeq2_jorstad_MTG_subclass_matchedGenes.qs")),
  "sea" = qread(file = file.path(Sys.getenv("REPO_DIR", "/home/gugene/code/git/kang-oldham-2026"), "figures/fig_1/DE_v2.4/DESeq2/seaad/DESeq2_seaad_MTG_subclass_matchedGenes.qs"))
) |>
  lapply(\(x){
    mapply(\(y,z){
      y$celltype <- z
      y$genes <- rownames(y)
      colnames(y)[c(2,5,6)] <- c("logFC", "PValue", "FDR")
      return(y)
    }, x, names(x), SIMPLIFY = F)
  }) # add columns for gene and ct
# Reorder both datasets to canonical cts order (DESeq2 objects are stored in a different order)
reslist <- lapply(reslist, \(d) d[match(as.character(cts), names(d))])

# Gather unique DE genes
uniquegenes <- lapply(list(edger, reslist), \(z){
  a <- lapply(z, \(y){
    do.call(rbind, y) |>
    dplyr::filter(!is.na(PValue)) 
  })
  lapply(a, \(x){
    ug <- list()
    for(i in seq_along(cts)){
      genesin <- x |> 
        dplyr::filter(celltype == cts[i],
                      FDR < 0.05)
                      #logFC >= 1) 
      genesout <- x |> 
        dplyr::filter(celltype != cts[i],
                      FDR < 0.05)
                      #logFC >= 1)   
      ug[[i]] <- genesin$genes[!genesin$genes %in% genesout$genes]
    } 
    names(ug) <- cts
    return(ug)
  })
}) |>
  set_names("edgeR", "DEseq2")

# Gather DE genes (FDR)
el <- lapply(edger, \(dataset){
  lapply(dataset, \(x) x$genes[x$FDR < 0.05])
})
rl <- lapply(reslist, \(dataset){
  lapply(dataset, \(x){
    out <- rownames(x)[x$FDR < 0.05] 
    return(out[!is.na(out)])
  })
})


###########
# Panel A
###########
plotmat <- lapply(cts, \(x){
  ind <- which(cts == x)
  outmat <- data.frame("value" = c(sum(!uniquegenes$edgeR[[1]][[ind]] %in% uniquegenes$DEseq2[[1]][[ind]]),
                                   sum(!uniquegenes$DEseq2[[1]][[ind]] %in% uniquegenes$edgeR[[1]][[ind]]),
                                   length(intersect(uniquegenes$edgeR[[1]][[ind]], uniquegenes$DEseq2[[1]][[ind]]))),
                       "Method" = c("edgeR", "DESeq2", "Both"),
                       "ct" = x)
  return(outmat)
}) |> do.call(what = "rbind") |>
  mutate(ct = cts_upper[match(ct, cts)])
ordervec <- plotmat |> group_by(ct) |> summarise(sum = sum(value)) |> arrange(sum)
plotmat$ct <- factor(plotmat$ct, levels = ordervec$ct)
plotmat$Method <- factor(plotmat$Method, levels = c("edgeR", "DESeq2", "Both"))

p <- ggplot(plotmat, aes(x = ct, y = value, fill = Method)) +
  theme_classic() + 
  geom_bar(position = "stack", stat = "identity", alpha = 0.6) +
  labs(x = "", y = "# unique markers") +
  theme(text = element_text(size = 14),
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 14),
        axis.text.y = element_text(size = 14),
        axis.title.y = element_text(size = 14, margin = margin(0,10,0,0)))  +
  paletteer::scale_fill_paletteer_d("khroma::highcontrast")

ggsave(p, file = file.path(save_dir, "panel_A.svg"), device = svglite::svglite, bg = "white", width = 10, height = 3)


############
# Panel B
###########
plotmat <- lapply(cts, \(x){
  ind <- which(cts == x)
  outmat <- data.frame("value" = c(sum(!uniquegenes$edgeR[[2]][[ind]] %in% uniquegenes$DEseq2[[2]][[ind]]),
                                   sum(!uniquegenes$DEseq2[[2]][[ind]] %in% uniquegenes$edgeR[[2]][[ind]]),
                                   length(intersect(uniquegenes$edgeR[[2]][[ind]], uniquegenes$DEseq2[[2]][[ind]]))),
                       "Method" = c("edgeR", "DESeq2", "Both"),
                       "ct" = x)
  return(outmat)
}) |> do.call(what = "rbind") |>
  mutate(ct = cts_upper[match(ct, cts)])
ordervec <- plotmat |> group_by(ct) |> summarise(sum = sum(value)) |> arrange(sum)
plotmat$ct <- factor(plotmat$ct, levels = ordervec$ct)
plotmat$Method <- factor(plotmat$Method, levels = c("edgeR", "DESeq2", "Both"))
p <- ggplot(plotmat, aes(x = ct, y = value, fill = Method)) +
  theme_classic() + 
  geom_bar(position = "stack", stat = "identity", alpha = 0.6) +
  labs(x = "", y = "# unique markers") +
  theme(text = element_text(size = 14),
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 14),
        axis.text.y = element_text(size = 14),
        axis.title.y = element_text(size = 14, margin = margin(0,10,0,0)))  +
  paletteer::scale_fill_paletteer_d("khroma::highcontrast")
ggsave(p, file = file.path(save_dir, "panel_B.svg"), device = svglite::svglite, bg = "white", width = 10, height = 3)


############
# Panel C
###########

allgenes <- unlist(uniquegenes) |> unique()
eulermat <- data.frame("edger_jorstad_unique" = allgenes %in% unique(unlist(uniquegenes[[1]][[1]])),
                       "edger_sea_unique" = allgenes %in% unique(unlist(uniquegenes[[1]][[2]])),
                       "DESeq2_jorstad_unique" = allgenes %in% unique(unlist(uniquegenes[[2]][[1]])),
                       "DESeq2_sea_unique" = allgenes %in% unique(unlist(uniquegenes[[2]][[2]]))
                       )
pdf(file = file.path(save_dir,"panel_C_euler.pdf"), bg = "white")  # renamed: panel_C.pdf now holds the UpSet (below)
plot(eulerr::euler(eulermat),
     #fills = alpha(c(paletteer::paletteer_d("khroma::highcontrast")[1:2], "#0E7175FF"), .6),
     labels = list(font = 1, cex = 1),
     quantities = list(cex = 1))
dev.off()
pdf(file = file.path(save_dir, "panel_C_euler_nolabels.pdf"), bg = "white")
plot(eulerr::euler(eulermat),
     #fills = alpha(c(paletteer::paletteer_d("khroma::highcontrast")[1:2], "#0E7175FF"), .6),
     labels = F)
dev.off()

#####
# Panel C redone
#####
# Count overlaps if they match celltypes
genelist <- list(uniquegenes[[1]][[1]],
                 uniquegenes[[1]][[2]],
                 uniquegenes[[2]][[1]],
                 uniquegenes[[2]][[2]])

comparison_names <- c("JE", "GE", "JD", "GD", 
                      "JE&GE", "JE&JD", "JE&GD", "GE&JD", "GE&GD", "JD&GD",
                      "JE&GE&JD", "JE&GE&GD", "JE&JD&GD", "GE&JD&GD",
                      "JE&GE&JD&GD")

comparison_names <- c("Jorstad_edgeR", "Gabitto_edgeR", "Jorstad_DESeq2", "Gabitto_DESeq2", 
                      "Jorstad_edgeR&Gabitto_edgeR", "Jorstad_edgeR&Jorstad_DESeq2", "Jorstad_edgeR&Gabitto_DESeq2", "Gabitto_edgeR&Jorstad_DESeq2", "Gabitto_edgeR&Gabitto_DESeq2", "Jorstad_DESeq2&Gabitto_DESeq2",
                      "Jorstad_edgeR&Gabitto_edgeR&Jorstad_DESeq2", "Jorstad_edgeR&Gabitto_edgeR&Gabitto_DESeq2", "Jorstad_edgeR&Jorstad_DESeq2&Gabitto_DESeq2", "Gabitto_edgeR&Jorstad_DESeq2&Gabitto_DESeq2",
                      "Jorstad_edgeR&Gabitto_edgeR&Jorstad_DESeq2&Gabitto_DESeq2")

comparisons <- list(combn(4,1),
                    combn(4,2),
                    combn(4,3),
                    combn(4,4))

shared_vec <- lapply(comparisons, \(comp){
  outvec <- c()
  for(i in 1:ncol(comp)){
    outvec[i] <- lapply(seq_along(cts), \(j){
      if(length(comp[ ,i]) == 1){
        included <- genelist[[comp[ ,i]]][[j]]
      } else {
        input1 <- lapply(genelist[comp[ ,i]], \(u) u[[j]])
        included <- Reduce(\(a, b){
          intersect(a, b)
        }, input1) 
      }

      input2 <- lapply(genelist[c(1:4)[-comp[ ,i]]], \(u) u[[j]])
      excluded <- Reduce(\(a, b){
        union(a, b)
      }, input2) 

      out <- included[!included %in% excluded]
      return(out)
    }) |>
      unlist() |> unique() |> length()
    #outvec[i] <- uni - nonuni 
  }
  return(outvec)
}) |> unlist()
names(shared_vec) = comparison_names

#####
# Panel C — UpSet (ported from make_panel_C.R)
# UpSetR fixes: stub grid.newpage() so the single-page vector device isn't blanked;
# patch Make_main_bar bottom-margin. mb.ratio shrinks the bar panel vs the dot matrix.
# Font sizes left at UpSetR defaults to match the original panel_C_upset_bottom.
# The y-axis title is suppressed here and added as a rotated text box during PPT assembly.
#####
# Apply UpSetR patches, capture the UpSet ONCE as a grob, then draw that grob to each
# single-page device. (Capturing avoids UpSetR's internal page advance, which otherwise
# leaves a blank page 1 in the PDF; grid.newpage is stubbed so the capture isn't blanked.)
.orig_newpage <- grid::grid.newpage
unlockBinding("grid.newpage", asNamespace("grid"))
assign("grid.newpage", function(...) invisible(NULL), envir = asNamespace("grid"))
.orig_mmb <- getFromNamespace("Make_main_bar", "UpSetR")
.mmb_src  <- sub("bottom_margin <- \\(-1\\) \\* 0\\.65", "bottom_margin <- 0",
                 paste(deparse(body(.orig_mmb)), collapse = "\n"))
.mmb_patched <- .orig_mmb; body(.mmb_patched) <- parse(text = .mmb_src)[[1]]
assignInNamespace("Make_main_bar", .mmb_patched, "UpSetR")

.draw_C <- function() print(UpSetR::upset(fromExpression(shared_vec),
  order.by        = "freq",
  mb.ratio        = c(0.6, 0.4),
  sets.x.label    = "# of DE genes",
  mainbar.y.label = "",
  queries = list(list(query = intersects,
    params = list("Jorstad_edgeR", "Gabitto_edgeR", "Jorstad_DESeq2", "Gabitto_DESeq2"),
    color = "orange", active = T))))

# SVG: draw directly so showtext bakes the sans font as vector paths (matches panels A/B;
# no font-family dependency, so it can't fall back to a serif on machines lacking the font).
svglite::svglite(file.path(save_dir, "panel_C.svg"), width = 5, height = 2.2, bg = "white")
.draw_C(); dev.off()
# PDF: capture once as a grob and draw to a single page (cairo_pdf embeds the font).
g_upsetC <- grid::grid.grabExpr(.draw_C())
cairo_pdf(file.path(save_dir, "panel_C.pdf"), width = 5, height = 2.2, bg = "white")
grid::grid.draw(g_upsetC); dev.off()

assign("grid.newpage", .orig_newpage, envir = asNamespace("grid"))
lockBinding("grid.newpage", asNamespace("grid"))
assignInNamespace("Make_main_bar", .orig_mmb, "UpSetR")
 
#########
# Panel D
# Table with three columns that lists each subclass from top to bottom ranked by # of reproducible marker genes (n=24). Column 1: subclass label; column 2: # markers; column 3: Top 5 markers (unique).
###########

# Collect shared markers
shared_markers <- lapply(cts, \(x){
  ind <- which(cts == x)
  int1 <- intersect(uniquegenes[[1]][[1]][[ind]], uniquegenes[[1]][[2]][[ind]])
  int2 <- intersect(uniquegenes[[2]][[1]][[ind]], uniquegenes[[2]][[2]][[ind]])
  intall <- intersect(int1, int2)
  return(intall)
}) 

# Collect mean ranks of markers per condition
mean_marker_ranks <- lapply(cts, \(x){
  ind <- which(cts == x)
  rlist <- lapply(list(edger[[1]][[ind]],
                       edger[[2]][[ind]],
                       reslist[[1]][[ind]],
                       reslist[[2]][[ind]]), \(y){
    y |> 
      mutate(rank = 1:nrow(y)) |>
      select(genes, rank)
  })
  rcombined <- Reduce(\(a, b){
    left_join(a, b, by = join_by(genes))
  }, rlist) 
  rcombined$mean_ranks <- rowMeans(rcombined[,2:5]) 
  rcombined <- rcombined[order(rcombined$mean_ranks), ]
  return(rcombined |> select(genes, mean_ranks))
})

# Using mean ranks, select top 5 shared DE genes per subclass
top5list <- mapply(\(x, y){
  y[y$genes %in% x, ] |>
    slice(1:5) |>
    pull(genes) |>
    paste(collapse = ", ")
}, shared_markers, mean_marker_ranks, SIMPLIFY = F) |>
  unlist()

# Create table
tab <- data.frame("Subclass" = cts_upper[match(names(el[[1]]), cts)], 
                  "Count" = lapply(shared_markers, length) |> unlist(),
                  "Top_5" = top5list) |>
  arrange(desc(Count))

tab1 <- gt(tab) |>
  cols_label(
    Subclass = html("Subclass"),
    Count = html("#"),
    Top_5 = html("Top markers")
  ) |>
  tab_options(
    column_labels.font.size = "smaller",
    table.font.size = "smaller",
    data_row.padding = px(3)
  )
gtsave(tab1, filename = file.path(save_dir, "panel_D.html"))
gtsave(tab1, filename = file.path(save_dir, "panel_D.pdf"))

##########
# Panel E
##########
metacell <- qread(file.path(Sys.getenv("DATA_DIR", "/mnt/bdata/gugene"), "data/greedy_march_pipeline_output/finalNonNorm_minsize10_unmerged/LeinMTG/sn_summary_tables/sn_summary_objects_log.qs"))$mean$Subclass
sn_anno <- fread(file.path(Sys.getenv("ESSA_DIR", "/home/gugene/code/git/ESSA"), "data/Lein_2023_cell_annotations_DFC.csv"), data.table = FALSE) # OK to use DFC file here (subclass->class mapping is region-independent)
sn_anno_subclass <- sn_anno[!duplicated(sn_anno$Cell_Type), c(1, 10)]
sn_anno_subclass <- sn_anno_subclass[match(colnames(metacell[[1]]), sn_anno_subclass$Cell_Type), ]

.ef_n_E <- nrow(metacell[[1]])  # gene count (rows) for the Panel E title, written to a sidecar below
metacell_cor <- lapply(metacell, cor)

# Calculate mean correlations for each class
# (computed on the original celltype names, which match sn_anno_subclass$Cell_Type;
#  display-name uppercasing is applied afterwards, just before the heatmap)
for(i in unique(sn_anno_subclass$Class)){
  subset <- sn_anno_subclass |>
    filter(Class == i) |>
    pull(Cell_Type)
  subset1 <- colnames(metacell_cor[[1]]) %in% subset
  temp <- metacell_cor[[1]][subset1, subset1]
  cat(i, " ", mean(temp[upper.tri(temp)]), "\n")
}
# Non-neuronal   0.5475125
# GABAergic   0.906187
# Glutamatergic   0.9393273

# Calculate mean correlation in all neuronal celltypes
subset <- sn_anno_subclass |>
    filter(Class != "Non-neuronal") |>
    pull(Cell_Type)
subset1 <- colnames(metacell_cor[[1]]) %in% subset
temp <- metacell_cor[[1]][subset1, subset1]
cat(i, " ", mean(temp[upper.tri(temp)]), "\n")
# 0.8948982

# Apply display names (uppercased) for the heatmap
colnames(metacell_cor[[1]]) <- cts_upper[match(colnames(metacell_cor[[1]]), cts)]
rownames(metacell_cor[[1]]) <- colnames(metacell_cor[[1]])

# Subclass
cc_colors <- RColorBrewer::brewer.pal(length(unique((sn_anno_subclass$Class))), "Set1")
names(cc_colors) <- unique(sn_anno_subclass$Class)
col_fun = circlize::colorRamp2(c(0, .5, 1), c("blue", "white", "red"))
column_ha = HeatmapAnnotation(`Cell class` = sn_anno_subclass$Class,
                              col = list(`Cell class`=cc_colors),
                              annotation_legend_param = list(
                                `Cell class` = list(
                                  title_gp = gpar(fontface = "plain") 
                                )
                              )
                              )

pdf(file.path(save_dir, "panel_E.pdf"))
hE <- Heatmap(metacell_cor[[1]],
             name = "Pearson cor",
             width = unit(0.8, "snpc"), # Adjust width to make cells square
             height = unit(0.8, "snpc"), # Adjust height to make cells square
             col = col_fun, 
             #left_annotation=row_ha, 
             top_annotation = column_ha,
             heatmap_legend_param = list(
               title_gp = gpar(fontface = "plain")
             ),
             row_names_gp = gpar(fontfamily = "sans"),       
             column_names_gp = gpar(fontfamily = "sans")
             #column_names_gp = gpar(fontsize=fontsize)
             )
draw(hE, merge_legend=T,
     heatmap_legend_side = "left",
     padding = unit(c(1, 1, 1, 1), "cm")
     )
dev.off()
.efE_cor <- metacell_cor[[1]]; .efE_cls <- sn_anno_subclass$Class  # for the combined E+F below

##########
# Panel F
##########

metacell <- qread(file.path(Sys.getenv("DATA_DIR", "/mnt/bdata/gugene"), "data/greedy_march_pipeline_output/finalNonNorm_minsize10_unmerged/SEAAD2024_AllADVsCon_MTG/sn_summary_tables/sn_summary_objects_log.qs"))$mean
sn_anno <- fread(data.table=F,file = file.path(Sys.getenv("DATA_DIR", "/mnt/bdata/gugene"), "datasets/SN_RNAseq/sea_ad_2024/mtg/RNAseq/SEAAD_MTG_RNAseq_final-nuclei.2024-02-13_metadata.csv")) %>%
  dplyr::filter(!`Neurotypical reference`)
sn_anno_subclass <- sn_anno |>
  select(Subclass, Class) |>
  filter(!duplicated(Subclass)) |>
  mutate(Class = case_match(
    Class, 
    "Neuronal: GABAergic" ~ "GABAergic",
    "Neuronal: Glutamatergic" ~ "Glutamatergic",
    "Non-neuronal and Non-neural" ~ "Non-neuronal"
  )) |>
  arrange(match(Subclass, colnames(metacell$Subclass$Control)))

.ef_n_F <- nrow(metacell$Subclass$Control)  # gene count (rows) for the Panel F title, written to a sidecar below
metacell_cor <- cor(metacell$Subclass$Control)

# Calculate mean correlations for each class
# (computed on the original Subclass names, which match sn_anno_subclass$Subclass;
#  display-name renaming is applied afterwards, just before the heatmap)
for(i in unique(sn_anno_subclass$Class)){
  subset <- sn_anno_subclass |>
    filter(Class == i) |>
    pull(Subclass)
  subset1 <- colnames(metacell_cor) %in% subset
  temp <- metacell_cor[subset1, subset1]
  cat(i, " ", mean(temp[upper.tri(temp)]), "\n")
}
# Non-neuronal   0.6598768
# GABAergic   0.9225615
# Glutamatergic   0.9453485

# Calculate mean correlations for all neuronal celltypes
subset <- sn_anno_subclass |>
    filter(Class != "Non-neuronal") |>
    pull(Subclass)
subset1 <- colnames(metacell_cor) %in% subset
temp <- metacell_cor[subset1, subset1]
cat(i, " ", mean(temp[upper.tri(temp)]), "\n")
# 0.9075513

# Apply display names for the heatmap: canonicalize SEAAD subclass labels BY VALUE (not by
# position, which silently mislabels if the metacell column order ever changes), then uppercase.
seaad_recode <- c("Astrocyte" = "Astro", "Endothelial" = "Endo", "Microglia-PVM" = "Micro/PVM", "Oligodendrocyte" = "Oligo")
hit <- colnames(metacell_cor) %in% names(seaad_recode)
colnames(metacell_cor)[hit] <- seaad_recode[colnames(metacell_cor)[hit]]
colnames(metacell_cor) <- cts_upper[match(colnames(metacell_cor), cts)]
rownames(metacell_cor) <- colnames(metacell_cor)

cc_colors <- RColorBrewer::brewer.pal(length(unique((sn_anno_subclass$Class))), "Set1")
names(cc_colors) <- unique(sn_anno_subclass$Class)
col_fun = circlize::colorRamp2(c(0, .5, 1), c("blue", "white", "red"))
column_ha = HeatmapAnnotation(`Cell class` = sn_anno_subclass$Class,
                              col = list(`Cell class`=cc_colors),
                              annotation_legend_param = list(
                                `Cell class` = list(
                                  title_gp = gpar(fontface = "plain") 
                                )
                              )
                              )

# bump the heatmap legend to the right so it clears the y-axis (row) labels
ht_opt$HEATMAP_LEGEND_PADDING <- unit(c(2, 8, 2, 2), "mm")  # c(bottom, left, top, right)
pdf(file.path(save_dir, "panel_F.pdf"))
hF <- Heatmap(metacell_cor,
             name = "Pearson cor",
             width = unit(0.8, "snpc"), # Adjust width to make cells square
             height = unit(0.8, "snpc"), # Adjust height to make cells square
             col = col_fun, 
             #left_annotation=row_ha, 
             top_annotation = column_ha,
             heatmap_legend_param = list(
               title_gp = gpar(fontface = "plain")
             ),
             row_names_gp = gpar(fontfamily = "sans"),       
             column_names_gp = gpar(fontfamily = "sans")
             #column_names_gp = gpar(fontsize=fontsize)
             )
draw(hF, merge_legend=T,
     heatmap_legend_side = "right",
     padding = unit(c(1, 1, 1, 1), "cm")
     )
dev.off()
.efF_cor <- metacell_cor; .efF_cls <- sn_anno_subclass$Class  # for the combined E+F below

# Gene counts (matrix rows) for the Panel E/F titles, read by assemble_figure.py to rewrite
# "n = <count> genes" in the slide (so the title always matches the data / region).
writeLines(c(paste0("jorstad=", .ef_n_E), paste0("gabitto=", .ef_n_F)),
           file.path(save_dir, "panel_EF_gene_counts.txt"))

##########
# Combined E + F  (canonical E+F panel consumed by assemble_figure.py)
# Legend convention: none on E, on the right for F. Build combined-only heatmaps with a FIXED,
# EQUAL cell size so E and F bodies render the same width (both panels are height-limited on
# this canvas, so a shared snpc -> identical body sizes). snpc is smaller than the 0.8 used by
# the individual panel_E/F.pdf so the dendrogram tops aren't clipped at this canvas height.
##########
EF_SNPC <- 0.62
mk_ef_combined <- function(m, cls) {
  ccc <- RColorBrewer::brewer.pal(length(unique(cls)), "Set1"); names(ccc) <- unique(cls)
  Heatmap(m, name = "Pearson cor", col = col_fun,
    width = unit(EF_SNPC, "snpc"), height = unit(EF_SNPC, "snpc"),
    top_annotation = HeatmapAnnotation(`Cell class` = cls, col = list(`Cell class` = ccc),
      show_annotation_name = FALSE,
      annotation_legend_param = list(`Cell class` = list(title = "",
        at = c("Glutamatergic", "GABAergic", "Non-neuronal"),
        title_gp = gpar(fontface = "plain")))),
    heatmap_legend_param = list(title_gp = gpar(fontface = "plain")),
    row_names_gp = gpar(fontfamily = "sans", fontsize = 10.5),       # slightly smaller than grid default 12
    column_names_gp = gpar(fontfamily = "sans", fontsize = 10.5))
}
##########
# Per-class mean correlation, annotated onto the canonical E+F panel: the mean r within each
# cell class (colored by class) and across all neuronal classes (black), each placed near the
# dendrogram node that spans that class's columns with a leader back to it. Replaces the eight
# labels that used to be typed into the slide by hand — those had gone stale against the data
# (they carry v2's values; v3 gives 0.93 / 0.69 for panel F's GABAergic / Non-neuronal).
#
# UNIT TRAP: the panels are captured by grid.grabExpr() on grid's DEFAULT 7x7in device and
# replayed by grid.arrange() into cells of 5.32in (E) and 7.18in (F). Native units rescale on
# replay; mm/pt do NOT. Laying labels out in mm therefore mis-places every anchor by that
# panel's grab/replay ratio (1.32 in E, 0.98 in F). So the layout below is done entirely in
# NATIVE units, and the one absolute quantity that has to cross over — the text's own size — is
# converted with a factor MEASURED at replay scale: pass 1 drops two sentinel dots at the
# dendrogram viewport's scale corners, their spacing is read back out of the SVG, and pass 2
# lays out with it. (Grabbing at the final cell size instead would change the panel's
# appearance, since fonts are absolute and everything else is relative. Decorating after
# grid.arrange is not possible either — the heatmap viewports do not survive the replay.)
##########
LAB_FS   <- 9     # pt
LEAD_PAD <- 0.6   # mm, gap between leader end and the text box
DX       <- 6.5   # mm, horizontal offset from node apex to the label box
DY       <- 4.5   # mm, the label sits this far above its node apex
ROW_GAP  <- 0.5   # mm, extra clearance when a label is raised onto a new row
BOX_PAD  <- 0.4   # mm, padding on the opaque backing box behind each label
MARGIN   <- 0.5   # mm, clearance a label keeps from dendrogram segments and other labels
# Leader line. R measures lty dash/gap lengths in multiples of lwd, so "12" (1 on, 2 off) stays
# denser than the "13" of lty="dotted" as the line thickens. The SVG is scaled ~0.44 into the
# page, so lwd 1.4 here lands at ~0.6 pt on the assembled figure.
LEAD_LWD <- 1.4
LEAD_LTY <- "12"
# Manual nudges, in mm, applied to the computed placement: NUDGE[[panel]][[class]] =
# c(dx, dy), dy positive = up. The automatic layout keeps labels off the dendrogram
# and off each other, but it has no opinion about a label sitting where a
# neighbour's leader begins, and it cannot lift one past the canvas edge. These are
# taste corrections on top of it, not positions -- the anchors stay data-derived, so
# a regenerated panel still moves its labels with the tree.
NUDGE <- list(
  E = list(Glutamatergic = c(0, 0), GABAergic = c(0, 0), `Non-neuronal` = c(0, 0), neuronal = c(0, 0)),
  F = list(Glutamatergic = c(0, 0), GABAergic = c(0, 0), `Non-neuronal` = c(0, 0), neuronal = c(0, 0))
)
SENTINEL <- c(E = "#010203", F = "#040506")   # calibration marks, pass 1 only
PT_MM    <- 2.834646
.vpscale <- list()   # each panel's dendrogram viewport scales, stashed for read_calib()

# walk a column dendrogram -> table of every node's leaf span, size, height, apex x, plus the
# segments the tree actually draws (one horizontal connector per node, one riser per child)
dend_node_table <- function(dend) {
  tab <- list(); segs <- list(); cnt <- new.env(); cnt$i <- 0L
  rec <- function(node) {
    if (is.leaf(node)) {
      cnt$i <- cnt$i + 1L
      info <- list(posmin = cnt$i, posmax = cnt$i, size = 1L,
                   height = attr(node, "height"), x = cnt$i - 0.5, label = attr(node, "label"))
      tab[[length(tab) + 1L]] <<- info; return(info)
    }
    kids <- lapply(node, rec)
    kx <- vapply(kids, `[[`, numeric(1), "x"); kh <- vapply(kids, `[[`, numeric(1), "height")
    h  <- attr(node, "height")
    segs[[length(segs) + 1L]] <<- data.frame(x0 = min(kx), x1 = max(kx), y0 = h, y1 = h)
    for (j in seq_along(kids))
      segs[[length(segs) + 1L]] <<- data.frame(x0 = kx[j], x1 = kx[j], y0 = kh[j], y1 = h)
    info <- list(posmin = min(vapply(kids, `[[`, numeric(1), "posmin")),
                 posmax = max(vapply(kids, `[[`, numeric(1), "posmax")),
                 size   = sum(vapply(kids, `[[`, integer(1), "size")),
                 height = h, x = mean(kx), label = NA_character_)
    tab[[length(tab) + 1L]] <<- info; info
  }
  rec(dend)
  leaves <- Filter(function(e) e$size == 1L, tab)
  list(nodes = do.call(rbind, lapply(tab, function(e)
         data.frame(posmin = e$posmin, posmax = e$posmax, size = e$size, height = e$height, x = e$x))),
       segs = do.call(rbind, segs),
       leaf_labels = vapply(leaves, `[[`, character(1), "label")[
         order(vapply(leaves, `[[`, numeric(1), "posmin"))])
}
# The class's dominant subtree: the LARGEST node whose leaf span lies entirely
# within P. For a monophyletic class this is exactly its MRCA, but a class need not
# be a clade -- in the MTG panel OPC clusters with the neurons, so the non-neuronal
# leaves have no common ancestor below the root, and anchoring on the MRCA pointed
# the label at the whole tree instead of at its own block. The value is still the
# mean over every member of the class; only the leader's target changes.
class_node <- function(nodes, P) {
  inside <- mapply(function(a, b) all(seq(a, b) %in% P), nodes$posmin, nodes$posmax)
  cand <- nodes[inside, , drop = FALSE]
  cand[which.max(cand$size), ]
}
draw_ef_annotated <- function(ht, cor_mat, cls, legend_side = "right", show_legend = TRUE,
                              panel = "E", calib = NULL) {
  htd <- draw(ht, merge_legend = TRUE, heatmap_legend_side = legend_side,
              show_heatmap_legend = show_legend, show_annotation_legend = show_legend,
              padding = unit(c(2, 2, 2, 2), "mm"))
  classes   <- intersect(c("Non-neuronal", "GABAergic", "Glutamatergic"), unique(cls))
  classmean <- sapply(classes, function(cl) { s <- cls == cl; sub <- cor_mat[s, s]; mean(sub[upper.tri(sub)]) })
  sN <- cls != "Non-neuronal"; subN <- cor_mat[sN, sN]; neuronal_mean <- mean(subN[upper.tri(subN)])
  ccc <- RColorBrewer::brewer.pal(length(unique(cls)), "Set1"); names(ccc) <- unique(cls)
  dt  <- dend_node_table(column_dend(htd)); nodes <- dt$nodes
  ord <- setNames(cls, colnames(cor_mat))[dt$leaf_labels]   # class per drawn leaf position
  items <- lapply(classes, function(cl) {
    nd <- class_node(nodes, which(ord == cl))
    list(x = nd$x, y = nd$height, v = classmean[cl], col = ccc[[cl]], key = cl) })
  ndN <- class_node(nodes, which(ord != "Non-neuronal"))
  items[[length(items) + 1L]] <- list(x = ndN$x, y = ndN$height, v = neuronal_mean,
                                      col = "#000000", key = "neuronal")
  decorate_column_dend("Pearson cor", {
    vp <- current.viewport(); xs <- vp$xscale; ys <- vp$yscale
    .vpscale[[panel]] <<- list(xs = xs, ys = ys)
    if (is.null(calib)) {
      grid.points(unit(xs, "native"), unit(ys, "native"), pch = 16, size = unit(0.4, "mm"),
                  gp = gpar(col = SENTINEL[[panel]]))
    } else {
      nx <- function(mm) mm / calib$mm_per_nx      # mm -> native x
      ny <- function(mm) mm / calib$mm_per_ny      # mm -> native y
      lab <- vapply(items, function(it) sprintf("r = %.2f", it$v), character(1))
      lw <- nx(convertWidth(grobWidth(textGrob(lab[1], gp = gpar(fontsize = LAB_FS))), "mm", TRUE))
      lh <- ny(convertHeight(grobHeight(textGrob(lab[1], gp = gpar(fontsize = LAB_FS))), "mm", TRUE))
      ax <- vapply(items, `[[`, numeric(1), "x"); ay <- vapply(items, `[[`, numeric(1), "y")
      # Free-slot search: the tree's own segments are obstacles (axis-aligned, so a segment hits
      # a label box exactly when their bounding boxes overlap), as are the labels already placed
      # and the panel edges. Each label takes the lowest free slot on a ladder rising from its
      # node, preferring the left side; the highest node goes first so it gets first claim on
      # the open space above the tree.
      segs <- dt$segs
      mx <- nx(MARGIN); my <- ny(MARGIN)
      # Ceiling: the ladder rises out of the dendrogram viewport into the canvas margin above
      # it, and without a bound a label runs off the top of the SVG and its glyphs are shaved
      # (Fig. S2's red label overshot by 0.83 pt). calib$head_mm is that margin, measured off
      # the same pass-1 sentinels, so the cap is in native units like everything else.
      ycap <- ys[2] + (calib$head_mm - MARGIN) / calib$mm_per_ny
      free <- function(bx0, by, placed) {
        bx1 <- bx0 + lw; by0 <- by - lh / 2; by1 <- by + lh / 2
        if (bx0 < xs[1] - mx || bx1 > xs[2] + mx || by1 > ycap) return(FALSE)
        if (any(segs$x0 <= bx1 + mx & segs$x1 >= bx0 - mx &
                segs$y0 <= by1 + my & segs$y1 >= by0 - my)) return(FALSE)
        for (p in placed)
          if (bx0 < p$x1 + mx && bx1 > p$x0 - mx && by0 < p$y1 + my && by1 > p$y0 - my) return(FALSE)
        TRUE
      }
      x0 <- y <- numeric(length(items)); right <- logical(length(items)); placed <- list()
      for (i in order(ay, decreasing = TRUE)) {
        cand <- NULL
        for (k in 0:14) {
          yk <- ay[i] + ny(DY) + k * (lh + ny(ROW_GAP))
          if (yk + lh / 2 > ycap) break                    # ladder has hit the ceiling
          for (rt in c(FALSE, TRUE)) {
            xk <- if (rt) ax[i] + nx(DX) else ax[i] - nx(DX) - lw
            if (free(xk, yk, placed)) { cand <- list(x0 = xk, y = yk, right = rt); break }
          }
          if (!is.null(cand)) break
        }
        if (is.null(cand))   # no free slot under the ceiling: sit as close to the node as fits
          cand <- list(x0 = ax[i] - nx(DX) - lw,
                       y = min(ay[i] + ny(DY), ycap - lh / 2), right = FALSE)
        x0[i] <- cand$x0; y[i] <- cand$y; right[i] <- cand$right
        placed[[length(placed) + 1L]] <- list(x0 = cand$x0, x1 = cand$x0 + lw,
                                              y0 = cand$y - lh / 2, y1 = cand$y + lh / 2)
      }
      # A nudge may use the last sliver of canvas that the automatic ceiling holds in
      # reserve, but never more: HARD_CAP leaves 0.15 mm above the label box, so the
      # glyph tops still cannot be shaved off the canvas edge.
      hard_cap <- ys[2] + (calib$head_mm - 0.15) / calib$mm_per_ny
      for (i in seq_along(items)) {
        nu <- NUDGE[[panel]][[items[[i]]$key]]
        if (!is.null(nu) && any(nu != 0)) {
          x0[i] <- min(max(x0[i] + nx(nu[1]), xs[1]), xs[2] - lw)   # keep it on the panel
          y[i]  <- min(y[i] + ny(nu[2]), hard_cap - lh / 2)
        }
      }

      # leaders first, then the labels on opaque backing boxes
      for (i in seq_along(items))
        grid.segments(unit(ax[i], "native"), unit(ay[i], "native"),
                      unit(if (right[i]) x0[i] - nx(LEAD_PAD) else x0[i] + lw + nx(LEAD_PAD), "native"),
                      unit(y[i] - ny(LEAD_PAD), "native"),
                      gp = gpar(col = items[[i]]$col, lty = LEAD_LTY, lwd = LEAD_LWD))
      for (i in seq_along(items)) {
        grid.rect(unit(x0[i] - nx(BOX_PAD), "native"), unit(y[i], "native"),
                  unit(lw + 2 * nx(BOX_PAD), "native"), unit(lh + 2 * ny(BOX_PAD), "native"),
                  just = c("left", "centre"), gp = gpar(fill = "white", col = NA))
        grid.text(lab[i], x = unit(x0[i], "native"), y = unit(y[i], "native"),
                  just = c("left", "centre"), gp = gpar(col = items[[i]]$col, fontsize = LAB_FS))
      }
    }
  })
}
# mm one native unit is worth after replay, measured off the pass-1 sentinels
read_calib <- function(path, colour, xs, ys) {
  s <- paste(readLines(path, warn = FALSE), collapse = "")
  hits <- regmatches(s, gregexpr(sprintf("<circle[^>]*fill: %s[^>]*>", colour), s,
                                 ignore.case = TRUE))[[1]]
  if (length(hits) < 2) stop("calibration sentinel ", colour, " not found in ", path)
  num <- function(h, a) as.numeric(sub(sprintf(".*%s='([-0-9.]+)'.*", a), "\\1", h))
  cx <- vapply(hits, num, numeric(1), "cx"); cy <- vapply(hits, num, numeric(1), "cy")
  list(mm_per_nx = (max(cx) - min(cx)) / diff(xs) / PT_MM,
       mm_per_ny = (max(cy) - min(cy)) / diff(ys) / PT_MM,
       head_mm   = min(cy) / PT_MM)   # canvas top edge -> top of the dendrogram viewport
}

hEc <- mk_ef_combined(.efE_cor, .efE_cls)
hFc <- mk_ef_combined(.efF_cor, .efF_cls)
render_ef <- function(path, calE = NULL, calF = NULL) {
  gEa <- grid::grid.grabExpr(draw_ef_annotated(hEc, .efE_cor, .efE_cls, show_legend = FALSE,
                                               panel = "E", calib = calE))
  gFa <- grid::grid.grabExpr(draw_ef_annotated(hFc, .efF_cor, .efF_cls, legend_side = "right",
                                               show_legend = TRUE, panel = "F", calib = calF))
  svglite::svglite(path, width = 12.5, height = 5.2, bg = "white")
  gridExtra::grid.arrange(gEa, gFa, ncol = 2, widths = c(1, 1.35))  # F wider to hold its legend
  dev.off()
}
.ef_pass1 <- tempfile(fileext = ".svg")
render_ef(.ef_pass1)
render_ef(file.path(save_dir, "panel_EF_combined.svg"),
          read_calib(.ef_pass1, SENTINEL[["E"]], .vpscale$E$xs, .vpscale$E$ys),
          read_calib(.ef_pass1, SENTINEL[["F"]], .vpscale$F$xs, .vpscale$F$ys))
unlink(.ef_pass1)

# ##########
# # Panel F (median)
# ##########

# metacell <- qread(file.path(Sys.getenv("DATA_DIR", "/mnt/bdata/gugene"), "data/greedy_march_pipeline_output/finalNonNorm_minsize10_unmerged/SEAAD2024_AllADVsCon_DFC/sn_summary_tables/sn_summary_objects_log.qs"))$median
# sn_anno <- fread(data.table=F,file = file.path(Sys.getenv("DATA_DIR", "/mnt/bdata/gugene"), "datasets/SN_RNAseq/sea_ad_2024/RNAseq/SEAAD_A9_RNAseq_final-nuclei_metadata.2024-02-13.csv")) %>%
#   dplyr::filter(!`Neurotypical reference`)
# sn_anno_subclass <- sn_anno |>
#   select(Subclass, Class) |>
#   filter(!duplicated(Subclass)) |>
#   mutate(Class = case_match(
#     Class, 
#     "Neuronal: GABAergic" ~ "GABAergic",
#     "Neuronal: Glutamatergic" ~ "Glutamatergic",
#     "Non-neuronal and Non-neural" ~ "Non-neuronal"
#   )) |>
#   arrange(match(Subclass, colnames(metacell$Subclass$Control)))

# metacell_cor <- cor(metacell$Subclass$Control)

# fixed_names <- c("Astro", "Chandelier", "Endo", "L2/3 IT","L4 IT", "L5 ET", "L5 IT", "L5/6 NP" ,"L6 CT","L6 IT",  
# "L6 IT Car3","L6b","Lamp5", "Lamp5 Lhx6", "Micro/PVM","Oligo", "OPC", "Pax6", "Pvalb", "Sncg", "Sst", "Sst Chodl","Vip","VLMC" )
# colnames(metacell_cor) <- fixed_names
# rownames(metacell_cor) <- fixed_names
# colnames(metacell_cor) <- cts_upper[match(colnames(metacell_cor[[1]]), cts)]
# rownames(metacell_cor) <- colnames(metacell_cor[[1]])

# # Calculate mean correlations for each class
# for(i in unique(sn_anno_subclass$Class)){
#   subset <- sn_anno_subclass |>
#     filter(Class == i) |>
#     pull(Subclass)
#   subset1 <- colnames(metacell_cor) %in% subset
#   temp <- metacell_cor[subset1, subset1]
#   cat(i, " ", mean(temp[upper.tri(temp)]), "\n")
# }
# # Non-neuronal   0.6598768 
# # GABAergic   0.9225615 
# # Glutamatergic   0.9453485 

# # Calculate mean correlations for all neuronal celltypes
# subset <- sn_anno_subclass |>
#     filter(Class != "Non-neuronal") |>
#     pull(Subclass)
# subset1 <- colnames(metacell_cor) %in% subset
# temp <- metacell_cor[subset1, subset1]
# cat(i, " ", mean(temp[upper.tri(temp)]), "\n")
# # 0.9075513

# cc_colors <- RColorBrewer::brewer.pal(length(unique((sn_anno_subclass$Class))), "Set1")
# names(cc_colors) <- unique(sn_anno_subclass$Class)
# col_fun = circlize::colorRamp2(c(0, .5, 1), c("blue", "white", "red"))
# column_ha = HeatmapAnnotation(`Cell class` = sn_anno_subclass$Class,
#                               col = list(`Cell class`=cc_colors),
#                               annotation_legend_param = list(
#                                 `Cell class` = list(
#                                   title_gp = gpar(fontface = "plain") 
#                                 )
#                               )
#                               )

# pdf(file.path(save_dir, "panel_F_median.pdf"))
# h <- Heatmap(metacell_cor,
#              name = "Pearson cor",
#              width = unit(0.8, "snpc"), # Adjust width to make cells square
#              height = unit(0.8, "snpc"), # Adjust height to make cells square
#              col = col_fun, 
#              #left_annotation=row_ha, 
#              top_annotation = column_ha,
#              heatmap_legend_param = list(
#                title_gp = gpar(fontface = "plain")
#              ),
#              row_names_gp = gpar(fontfamily = "sans"),       
#              column_names_gp = gpar(fontfamily = "sans")
#              #column_names_gp = gpar(fontsize=fontsize)
#              )
# draw(h, merge_legend=T,
#      heatmap_legend_side = "right",
#      padding = unit(c(1, 1, 1, 1), "cm")
#      )
# dev.off()
