# ad_db: Alzheimer's disease gene database for DFC and MTG brain regions
# Rebuilt 2026-07-22 from dfc_overlaps.csv / mtg_overlaps.csv via pre-fetched-PMID Sonnet-5 literature review + prefilter DB
# n = number of AD-linked papers (up to 5; "5+" if more); n = 1 for curated-database genes
# ref = PMID of most relevant reference (literature genes); ref = "website" for database-sourced genes

ad_db_dfc <- list(

  # APP processing / trafficking
  N4BP2L1 = list(n = 3, ref = 38345408),  # N4BP2L1 is an intracellular binding partner of MT5-MMP that significantly increases MT5-MM...
  NAPG = list(n = 1, ref = 20205790),  # A yeast two-hybrid screen using full-length APP as bait identified NAPG as a novel APP-int...
  NRDC = list(n = 2, ref = 23954170),  # Nardilysin (NRDC) enhances ADAM-mediated α-secretase cleavage of APP, precluding Aβ genera...
  RABGAP1 = list(n = 1, ref = 40859033),  # RABGAP1 binds the YENPTY motif in the APP cytosolic tail, and its Rab-GAP activity on endo...
  RTN3 = list(n = 3, ref = 27883331),  # RTN3 binds BACE1 and negatively modulates its beta-secretase activity; RTN3 deficiency ele...
  SEC31A = list(n = 2, ref = 32885474),  # Sec31A, a COPII coat protein at ER exit sites, is required for normal AbetaPP trafficking;...
  SENP1 = list(n = "5+", ref = 29862363),  # SENP1 deSUMOylates APP, reducing amyloid-beta production; DAPK1-mediated SENP1 degradation...

  # Amyloid-beta generation / aggregation / clearance
  SCRN3 = list(n = 1, ref = 37149819),  # Quantitative proteomics of AD prefrontal cortex identified SCRN3 as a novel disease-associ...
  XRCC5 = list(n = 2, ref = 27376156),  # Reduced Ku80 (XRCC5)/DNA-PK non-homologous end-joining activity occurs in AD brain; Ku80 d...

  # Tau phosphorylation / clearance
  MAPK8 = list(n = "5+", ref = 11954673),  # JNK (MAPK8)/c-Jun cascade is activated in AD neurons, driving tau phosphorylation and neur...
  PPP2R2B = list(n = "5+", ref = 33426524),  # PPP2R2B, a PP2A regulatory subunit governing tau dephosphorylation, shows a genome-wide-si...
  PPP3CB = list(n = "10+", ref = 8294942),  # [curator] PPP3CB encodes the calcineurin A catalytic subunit; calcineurin dephosphorylates tau and i...
  USP10 = list(n = 3, ref = 35987808),  # USP10 deubiquitinates tau, promoting its aggregation; USP10 is upregulated in AD brains an...

  # Ubiquitin-proteasome system
  CUL4B = list(n = 2, ref = 27325702),  # CUL4B, part of CRL4 E3 ubiquitin ligase complexes (CRL4-CRBN), interacts with the APP cyto...
  PAFAH1B1 = list(n = 1, ref = 33754896),  # PAFAH1B1 (LIS1) was identified as one of seven hub ubiquitin-proteasome system (E3 ligase-...

  # Mitochondrial dysfunction
  FASTKD2 = list(n = 2, ref = 25385369),  # FASTKD2, a mitochondria-related gene, is differentially expressed in AD astrocytes, and a ...
  GPR107 = list(n = 3, ref = 39048031),  # Neuronostatin signals through GPR107 to impair mitochondrial bioenergetics (ROS, ATP, memb...
  LRPPRC = list(n = 4, ref = 32497722),  # LRPPRC (mtRNA-stabilizing protein LRP130) expression is reduced in AD frontal cortex along...
  NDUFS1 = list(n = 1, ref = 33634105),  # Dauricine treatment ameliorates AD-like pathology in 3xTg-AD mice partly by modulating mit...
  SLC31A1 = list(n = 3, ref = 41739158),  # Amyloid-beta42 upregulates the copper importer SLC31A1, driving cuproptosis (copper-induce...

  # Endosomal-lysosomal trafficking
  APPL1 = list(n = "5+", ref = 26194181),  # APPL1, a rab5 effector, is recruited by the APP-beta-CTF fragment to endosomes, driving pa...
  EXT2 = list(n = 1, ref = 29752409),  # CRISPR knockout of the heparan-sulfate synthesis enzyme EXT2 significantly reduces cell-su...
  PDCD6IP = list(n = 4, ref = 32731849),  # PDCD6IP/Alix (ESCRT component) directs APP trafficking into extracellular vesicles, is ele...

  # ER stress / UPR / ERAD
  COPA = list(n = 1, ref = 41942750),  # COPA, a COPI coatomer subunit, co-complexes with the AD risk protein SorLA (SORL1) at the ...
  EDEM3 = list(n = 3, ref = 35970828),  # [curator] EDEM3 is an ER mannosidase mediating ERAD of misfolded glycoproteins; UPR/ERAD impairment ...
  QRICH1 = list(n = 1, ref = 39505222),  # QRICH1 is elevated in APP/PS1 mouse brain alongside other ER-stress/unfolded-protein-respo...

  # Synaptic failure / loss
  RPS6 = list(n = 4, ref = 41416952),  # Astrocyte-derived, Abeta-induced extracellular vesicles deliver RPS6 to axons to regulate ...
  SEPTIN6 = list(n = 1, ref = 40937833),  # A septin 6/7 'molecular glue' (REM127) that restores septin filament integrity was tested ...
  SH3GL2 = list(n = 4, ref = 38759013),  # Endophilin A1 (SH3GL2) is a synaptic-vesicle-recycling hub gene significantly downregulate...
  SPTAN1 = list(n = 5, ref = 26051930),  # [curator] Calpain cleaves αII-spectrin (SPTAN1), generating SBDP120 fragments that accumulate with a...
  STX7 = list(n = 3, ref = 33646358),  # STX7 is a presynaptic syntaxin whose greater abundance associates with worse cognitive per...
  WASL = list(n = 3, ref = 41806350),  # N-WASP (WASL) mediates Rac1-N-WASP-Arp2/3 actin polymerization required for synapse format...

  # Neuroinflammation
  AKT3 = list(n = "5+", ref = 33220166),  # AKT3 is down-regulated in AD brain/blood and mediates Abeta-induced neuroinflammation and ...
  IREB2 = list(n = 3, ref = 42159858),  # A pro-inflammatory IREB2+ microglial subpopulation is expanded in AD brain; IREB2 knockdow...
  PANX1 = list(n = 4, ref = 34068881),  # Pannexin-1 (PANX1) hemichannels release ATP and other danger signals that activate puriner...

  # Ca2+ dysregulation
  ATP2A2 = list(n = 4, ref = 29663107),  # ATP2A2 encodes SERCA2, the ER Ca2+-ATPase whose dysregulation disrupts neuronal Ca2+ homeo...
  STIM2 = list(n = "5+", ref = 28087881),  # STIM2 senses ER calcium depletion and mediates store-operated calcium entry (SOCE) in neur...
  TMEM35A = list(n = 5, ref = 34446574),  # NACHO (TMEM35A) chaperones assembly of Ca2+-permeable α7 nicotinic receptors; Aβ-driven lo...

  # AD genome-wide association (GWAS)
  ANKH = list(n = 3, ref = 39778705),  # ANKH lies in a locus enriched for protective alleles in AD-resistant centenarians and was ...
  CNOT7 = list(n = 2, ref = 33757599),  # A GWAS of cognitive resilience to brain amyloidosis identified a genome-wide-significant, ...
  EXOC4 = list(n = 1, ref = 23978990),  # Genome-wide homozygosity mapping in Caribbean Hispanics identified a recessive AD-associat...
  RBL2 = list(n = 1, ref = 41601569),  # Mendelian randomization on AD methylation datasets identified RBL2 (cg00000029) as causall...

  # Prefilter database entries
  ADGRB3 = list(n = 1, ref = "platform.opentargets.org"),  # adhesion G protein-coupled receptor B3; AD-associated in OpenTargets_Platform
  ANKMY2 = list(n = 1, ref = "platform.opentargets.org"),  # ankyrin repeat and MYND domain containing 2; AD-associated in OpenTargets_Platform
  APLP2 = list(n = 1, ref = "platform.opentargets.org"),  # amyloid beta precursor like protein 2; AD-associated in OMIM
  APPBP2 = list(n = 1, ref = "platform.opentargets.org"),  # amyloid beta precursor protein binding protein 2; AD-associated in OMIM
  CCNT2 = list(n = 1, ref = "platform.opentargets.org"),  # cyclin T2; AD-associated in OpenTargets_Platform
  CEP57 = list(n = 1, ref = "platform.opentargets.org"),  # centrosomal protein 57; AD-associated in OpenTargets_Platform
  CEP68 = list(n = 1, ref = "platform.opentargets.org"),  # centrosomal protein 68; AD-associated in OpenTargets_Platform
  CKAP5 = list(n = 1, ref = "platform.opentargets.org"),  # cytoskeleton associated protein 5; AD-associated in OpenTargets_Platform
  CSNK1G3 = list(n = 1, ref = "platform.opentargets.org"),  # casein kinase 1 gamma 3; AD-associated in OpenTargets_Platform
  CYRIB = list(n = 1, ref = "platform.opentargets.org"),  # CYFIP related Rac1 interactor B; AD-associated in OpenTargets_Platform
  DNM1L = list(n = 1, ref = "platform.opentargets.org"),  # dynamin 1 like; AD-associated in OMIM
  ERCC8 = list(n = 1, ref = "platform.opentargets.org"),  # ERCC excision repair 8, CSA ubiquitin ligase complex subunit; AD-associated in OpenTargets_Platform
  KLHL42 = list(n = 1, ref = "platform.opentargets.org"),  # kelch like family member 42; AD-associated in OpenTargets_Platform
  MTMR2 = list(n = 1, ref = "platform.opentargets.org"),  # myotubularin related protein 2; AD-associated in OpenTargets_Platform
  PHF3 = list(n = 1, ref = "platform.opentargets.org"),  # PHD finger protein 3; AD-associated in OpenTargets_Platform
  PHKB = list(n = 1, ref = "platform.opentargets.org"),  # phosphorylase kinase regulatory subunit beta; AD-associated in OpenTargets_Platform
  RPL23 = list(n = 1, ref = "platform.opentargets.org"),  # ribosomal protein L23; AD-associated in OpenTargets_Platform
  SCAPER = list(n = 1, ref = "platform.opentargets.org"),  # S-phase cyclin A associated protein in the ER; AD-associated in OpenTargets_Platform
  TAX1BP1 = list(n = 1, ref = "platform.opentargets.org"),  # Tax1 binding protein 1; AD-associated in OpenTargets_Platform
  TUBA1B = list(n = 1, ref = "platform.opentargets.org"),  # tubulin alpha 1b; AD-associated in OpenTargets_Platform
  TUBA4A = list(n = 1, ref = "platform.opentargets.org"),  # tubulin alpha 4a; AD-associated in OMIM; OpenTargets_Platform
  TUBB = list(n = 1, ref = "platform.opentargets.org"),  # tubulin beta class I; AD-associated in OpenTargets_Platform
  TUBB2A = list(n = 1, ref = "platform.opentargets.org"),  # tubulin beta 2A class IIa; AD-associated in OpenTargets_Platform
  TUBB3 = list(n = 1, ref = "platform.opentargets.org"),  # tubulin beta 3 class III; AD-associated in OpenTargets_Platform
  TUBB4B = list(n = 1, ref = "platform.opentargets.org"),  # tubulin beta 4B class IVb; AD-associated in OpenTargets_Platform
  UBE3B = list(n = 1, ref = "platform.opentargets.org"),  # ubiquitin protein ligase E3B; AD-associated in OpenTargets_Platform
  UBE4B = list(n = 1, ref = "platform.opentargets.org"),  # ubiquitination factor E4B; AD-associated in OpenTargets_Platform
  USP44 = list(n = 1, ref = "platform.opentargets.org"),  # ubiquitin specific peptidase 44; AD-associated in OpenTargets_Platform
  VCPIP1 = list(n = 1, ref = "platform.opentargets.org"),  # valosin containing protein interacting protein 1; AD-associated in OpenTargets_Platform
  VPS13C = list(n = 1, ref = "platform.opentargets.org"),  # vacuolar protein sorting 13 homolog C; AD-associated in OpenTargets_Platform
  ZBTB24 = list(n = 1, ref = "platform.opentargets.org"),  # zinc finger and BTB domain containing 24; AD-associated in OpenTargets_Platform
  ZNF287 = list(n = 1, ref = "platform.opentargets.org")  # zinc finger protein 287; AD-associated in OpenTargets_Platform
)

ad_db_mtg <- list(

  # APP processing / trafficking
  CLSTN1 = list(n = 3, ref = 32467230),  # Calsyntenin-1/Alcadein-alpha complexes with APP and adaptor X11-like to suppress amyloidog...
  CLSTN3 = list(n = "5+", ref = 39122814),  # CLSTN3 (Alcadein beta) is processed by the same secretases as APP; Alcbeta-deficient mice ...
  EXOC5 = list(n = 2, ref = 42039580),  # EXOC5, a subunit of the insulin-sensitive exocyst complex, closely associates with and tra...
  HPRT1 = list(n = "5+", ref = 28192196),  # HPRT1 mutations in Lesch-Nyhan disease show epistasis with APP, altering APP pre-mRNA spli...
  N4BP2L1 = list(n = 3, ref = 38345408),  # N4BP2L1 is an intracellular binding partner of MT5-MMP that significantly increases MT5-MM...
  NAPG = list(n = 1, ref = 20205790),  # A yeast two-hybrid screen using full-length APP as bait identified NAPG as a novel APP-int...
  NRDC = list(n = 2, ref = 23954170),  # Nardilysin (NRDC) enhances ADAM-mediated α-secretase cleavage of APP, precluding Aβ genera...
  PIKFYVE = list(n = 4, ref = 26862204),  # APP directly binds the PIKFYVE complex (via VAC14) and modulates its PI(3,5)P2-generating ...
  RAB11FIP5 = list(n = 1, ref = 40721030),  # RAB11FIP5 is the Rab11 adaptor bound by NCAM2's intracellular domain, mediating endocytosi...
  RTN1 = list(n = 4, ref = 28733667),  # RTN1 modulates BACE1 secretase activity and is differentially associated with senile plaqu...
  RTN3 = list(n = 3, ref = 27883331),  # RTN3 binds BACE1 and negatively modulates its beta-secretase activity; RTN3 deficiency ele...
  SEC24A = list(n = 2, ref = 34292306),  # Sec24A is the COPII cargo adaptor that selectively sorts presenilin-1 for ER exit during s...
  SEC31A = list(n = 2, ref = 32885474),  # Sec31A, a COPII coat protein at ER exit sites, is required for normal AbetaPP trafficking;...
  SPOCK1 = list(n = 1, ref = 27486134),  # Testican-1 (SPOCK1) accumulates and co-aggregates with Aβ plaques in AD cortex and CSF; AP...
  TSPAN5 = list(n = "5+", ref = 23035126),  # TSPAN5 belongs to the TspanC8 tetraspanin subgroup required for ER exit, maturation and tr...

  # Amyloid-beta generation / aggregation / clearance
  ABCG4 = list(n = "5+", ref = 27196068),  # ABCG4 mediates amyloid-beta efflux across the blood-brain barrier and, together with ABCG1...
  ATP11B = list(n = 2, ref = 40123832),  # ATP11B regulates microglial lipid metabolism; its deficiency causes pathological lipid dro...
  GGCT = list(n = 1, ref = 39949960),  # GGCT-generated pyroglutamic acid promotes oxidative-stress-driven protein aggregation, wit...
  PREPL = list(n = 2, ref = 37147110),  # PREPL is downregulated in late-onset AD brain; PREPL knockdown modulates protein trafficki...
  RAB22A = list(n = 2, ref = 29423001),  # Rab22a mediates hypoxia-induced CD147-Hook1 interaction that drives amyloid-beta accumulat...
  RANBP9 = list(n = "5+", ref = 19729516),  # RanBP9 scaffolds APP/BACE1/LRP complexes to boost amyloid-beta generation, also enhances t...
  SCRN3 = list(n = 1, ref = 37149819),  # Quantitative proteomics of AD prefrontal cortex identified SCRN3 as a novel disease-associ...
  TPP2 = list(n = 1, ref = 27699588),  # TPPII (TPP2) is required for degradation of Aβ peptides in human fibroblasts and modulates...
  UBE2N = list(n = 2, ref = 39015037),  # Age-dependent increase of UBE2N drives K63-linked ubiquitination and misfolded protein acc...
  WASF1 = list(n = 2, ref = 26280122),  # The APP intracellular domain downregulates WASF1/WAVE1 as a negative-feedback mechanism li...
  XRCC5 = list(n = 2, ref = 27376156),  # Reduced Ku80 (XRCC5)/DNA-PK non-homologous end-joining activity occurs in AD brain; Ku80 d...

  # Tau phosphorylation / clearance
  CUL5 = list(n = 2, ref = 37398204),  # The E3 ubiquitin ligase CRL5(SOCS4), containing CUL5, ubiquitinates tau and is a potent mo...
  GSKIP = list(n = 2, ref = 31640277),  # GSKIP anchors PKA and GSK3beta to increase PKA-mediated Tau phosphorylation (Ser409/214/26...
  MAPK8 = list(n = "5+", ref = 11954673),  # JNK (MAPK8)/c-Jun cascade is activated in AD neurons, driving tau phosphorylation and neur...
  MARCHF7 = list(n = 1, ref = 24905733),  # Axotrophin/MARCH7 binds tau and mono-ubiquitinates 4-repeat tau, reducing its microtubule-...
  PPM1A = list(n = 2, ref = 36388134),  # PPM1A activity is repressed in AD patient brain and 3xTg-AD mice; restoring PPM1A (via ove...
  PPP2CA = list(n = 2, ref = 36001963),  # A CRISPR-Cas9 screen identified PPP2CA (a PP2A catalytic subunit and tau phosphatase compo...
  PPP2R2B = list(n = "5+", ref = 33426524),  # PPP2R2B, a PP2A regulatory subunit governing tau dephosphorylation, shows a genome-wide-si...
  PPP2R2C = list(n = 1, ref = 32291379),  # PPP2R2C, encoding the brain-specific PP2A regulatory subunit PR55/B-gamma, is downregulate...
  PPP3CB = list(n = "10+", ref = 8294942),  # [curator] PPP3CB encodes the calcineurin A catalytic subunit; calcineurin dephosphorylates tau and i...
  PRKAA2 = list(n = 3, ref = 28717968),  # AMPK catalytic subunit PRKAA2 activity links to tau pathology: CB2 receptor deletion cause...
  RPL24 = list(n = 1, ref = 38554950),  # Cross-study proteomic/transcriptomic network analysis of AD hippocampus identified RPL24 a...
  TAOK1 = list(n = 4, ref = 14517247),  # TAOK1 (MARKK) is the Ste20-family kinase that activates MARK/PAR-1, driving pathological t...
  USP10 = list(n = 3, ref = 35987808),  # USP10 deubiquitinates tau, promoting its aggregation; USP10 is upregulated in AD brains an...
  YWHAZ = list(n = 3, ref = 40329321),  # CSF 14-3-3zeta (YWHAZ) levels are strongly associated with tau pathology (and Abeta) as in...

  # Autophagy-lysosome pathway
  ATP6V1B2 = list(n = "5+", ref = 36843263),  # The V-ATPase subunit ATP6V1B2 binds hyperphosphorylated tau, disrupting V-ATPase activity ...
  MAP1LC3B = list(n = 2, ref = 39044253),  # LC3B mediates astrocytic autophagic clearance of Aβ; astrocyte-specific LC3B knockdown inc...
  NCOA4 = list(n = "5+", ref = 39586368),  # NCOA4 is the master receptor for ferritinophagy (selective autophagic ferritin degradation...
  TIPRL = list(n = 2, ref = 34683848),  # TIPRL was identified as an upregulated differentially expressed gene common across AD micr...
  USP9X = list(n = 2, ref = 40586131),  # USP9X deubiquitinates Raptor, impairing autophagy-mediated clearance and promoting tau acc...

  # Ubiquitin-proteasome system
  CUL1 = list(n = 3, ref = 12354302),  # CUL1, core subunit of the SCF E3 ubiquitin ligase, is a hub gene downregulated across AD b...
  HACE1 = list(n = 3, ref = 29430571),  # HACE1, an E3 ubiquitin ligase, is implicated in AD via ubiquitin-proteasome-mediated prote...
  HECW2 = list(n = 1, ref = 38176925),  # HECW2 was identified as a ubiquitin-proteasome-system-related hub gene with altered expres...
  NDFIP1 = list(n = 2, ref = 29937728),  # Ndfip1 targets DMT1 for ubiquitin-mediated degradation; reduced Ndfip1 in APP/PS1 mouse br...
  PAFAH1B1 = list(n = 1, ref = 33754896),  # PAFAH1B1 (LIS1) was identified as one of seven hub ubiquitin-proteasome system (E3 ligase-...
  RCHY1 = list(n = 3, ref = 38740775),  # Pirh2 (RCHY1), an E3 ubiquitin ligase, is upregulated in AD models and modulates mitochond...
  TRIM32 = list(n = 4, ref = 17032350),  # TRIM32, an E3 ubiquitin ligase, is altered in AD brain alongside disturbed ubiquitin-prote...
  UBE2O = list(n = 3, ref = 37182872),  # UBE2O, an E2-E3 hybrid ubiquitin ligase, declines with age in AD brain and neurons; restor...
  USP14 = list(n = 3, ref = 28372990),  # USP14, a proteasome-associated deubiquitinase, delays proteasomal clearance of ubiquitinat...

  # Mitochondrial dysfunction
  BNIP3 = list(n = "5+", ref = 39972387),  # BNIP3 is a receptor-mediated mitophagy protein (with PINK1/Parkin and FUNDC1) implicated i...
  DLAT = list(n = 3, ref = 39759399),  # DLAT, the E2 subunit of the mitochondrial pyruvate dehydrogenase complex, undergoes copper...
  FASTKD2 = list(n = 2, ref = 25385369),  # FASTKD2, a mitochondria-related gene, is differentially expressed in AD astrocytes, and a ...
  GFM1 = list(n = 2, ref = 39952508),  # GFM1, a mitochondrial translation factor, is a hub gene linked to hereditary AD mitochondr...
  MRPS30 = list(n = 1, ref = 39920860),  # Bioinformatics/machine-learning analysis identified MRPS30 as a mitochondrial-immune bioma...
  NDUFS1 = list(n = 1, ref = 33634105),  # Dauricine treatment ameliorates AD-like pathology in 3xTg-AD mice partly by modulating mit...
  OCIAD1 = list(n = 4, ref = 31931285),  # OCIAD1/Asrij is elevated in AD brain and mouse models; it impairs mitochondrial function (...
  OPA1 = list(n = 2, ref = 37434203),  # OPA1, a mitochondrial fusion GTPase, is dysregulated in AD; OPA1 overexpression alleviates...
  OXR1 = list(n = 2, ref = 36172098),  # Oxidation resistance 1 (OXR1) is downregulated by miR-668-3p, promoting p53-p21-mediated o...
  TOMM7 = list(n = 2, ref = 41861196),  # TOMM7, a subunit of the outer mitochondrial membrane translocase, is a bioinformatically i...
  VDAC1 = list(n = "5+", ref = 36578022),  # VDAC1, the mitochondrial gatekeeper controlling Ca2+/metabolite flux and apoptosis, is ove...

  # Endosomal-lysosomal trafficking
  APPL1 = list(n = "5+", ref = 26194181),  # APPL1, a rab5 effector, is recruited by the APP-beta-CTF fragment to endosomes, driving pa...
  EXT2 = list(n = 1, ref = 29752409),  # CRISPR knockout of the heparan-sulfate synthesis enzyme EXT2 significantly reduces cell-su...
  HS6ST2 = list(n = 1, ref = 29752409),  # CRISPR knockout of the sulfotransferase HS6ST2 significantly reduces cell-surface tau aggr...
  PDCD6IP = list(n = 4, ref = 32731849),  # PDCD6IP/Alix (ESCRT component) directs APP trafficking into extracellular vesicles, is ele...
  SLC9A6 = list(n = 5, ref = 34617884),  # NHE6 (SLC9A6) regulates recycling-endosome pH; its loss impairs endolysosomal/autophagic t...
  SYNJ1 = list(n = 4, ref = 32493451),  # Synaptojanin 1 (SYNJ1) mediates synaptic-vesicle/endosomal phosphoinositide processing; it...
  VPS41 = list(n = 1, ref = 30508205),  # Vps41, a lysosomal-trafficking protein, is neuroprotective against Abeta-induced neurodege...

  # ER stress / UPR / ERAD
  ARCN1 = list(n = 1, ref = 41942750),  # ARCN1, a COPI coatomer subunit, is identified as co-enriched with the AD risk protein SorL...
  COPA = list(n = 1, ref = 41942750),  # COPA, a COPI coatomer subunit, co-complexes with the AD risk protein SorLA (SORL1) at the ...
  DDX1 = list(n = 3, ref = 39268577),  # DDX1 is an exome-wide-significant AD/dementia risk gene (UK Biobank) and a core subunit of...
  EDEM3 = list(n = 3, ref = 35970828),  # [curator] EDEM3 is an ER mannosidase mediating ERAD of misfolded glycoproteins; UPR/ERAD impairment ...
  EIF2A = list(n = 3, ref = 36227739),  # eIF2A (eIF2alpha) phosphorylation, a core UPR/ER-stress node, mediates ethanol-induced BAC...
  QRICH1 = list(n = 1, ref = 39505222),  # QRICH1 is elevated in APP/PS1 mouse brain alongside other ER-stress/unfolded-protein-respo...

  # Synaptic failure / loss
  ARHGEF7 = list(n = 1, ref = 40598577),  # Arhgef7 in prefrontal cortex neurons protects against amyloid-beta toxicity via Wnt signal...
  ATAD1 = list(n = 1, ref = 40849350),  # ATAD1, a key regulator of glutamatergic synapses, is down-regulated in AD brain tissue alo...
  CLTC = list(n = 2, ref = 34979241),  # In the AppNL-F amyloid knock-in mouse model, clathrin heavy chain (CLTC) shows altered pro...
  FMN2 = list(n = 2, ref = 28768717),  # The actin nucleator Formin 2 (FMN2) is deregulated in AD patients; Fmn2-deficient mice sho...
  PCMT1 = list(n = 2, ref = 38181970),  # PCMT1 (PIMT) knockout mice display AD-like synaptic plasticity deficits, impaired spatial ...
  SEPTIN6 = list(n = 1, ref = 40937833),  # A septin 6/7 'molecular glue' (REM127) that restores septin filament integrity was tested ...
  SH3GL2 = list(n = 4, ref = 38759013),  # Endophilin A1 (SH3GL2) is a synaptic-vesicle-recycling hub gene significantly downregulate...
  SNAP25 = list(n = "5+", ref = 33803217),  # SNAP25 is a core SNARE synaptic-vesicle-fusion protein whose CSF/plasma levels are a valid...
  SPTAN1 = list(n = 5, ref = 26051930),  # [curator] Calpain cleaves αII-spectrin (SPTAN1), generating SBDP120 fragments that accumulate with a...
  STXBP5 = list(n = 1, ref = 33646358),  # STXBP5 (tomosyn), a presynaptic SNARE-regulatory protein, shows elevated abundance associa...
  SYT4 = list(n = 2, ref = 38759013),  # Synaptotagmin-4 (SYT4) is a synaptic-vesicle-cycle hub gene downregulated in AD transgenic...
  WASL = list(n = 3, ref = 41806350),  # N-WASP (WASL) mediates Rac1-N-WASP-Arp2/3 actin polymerization required for synapse format...

  # Neuroinflammation
  AKT3 = list(n = "5+", ref = 33220166),  # AKT3 is down-regulated in AD brain/blood and mediates Abeta-induced neuroinflammation and ...
  CD200 = list(n = "5+", ref = 37801139),  # CD200-CD200R signaling between neurons and microglia suppresses microglial activation; red...
  IREB2 = list(n = 3, ref = 42159858),  # A pro-inflammatory IREB2+ microglial subpopulation is expanded in AD brain; IREB2 knockdow...
  PANX1 = list(n = 4, ref = 34068881),  # Pannexin-1 (PANX1) hemichannels release ATP and other danger signals that activate puriner...
  TPM1 = list(n = 3, ref = 35148456),  # TPM1 is upregulated in an AD mouse model where it drives neuroinflammation and neuronal re...

  # Ca2+ dysregulation
  ATP2A2 = list(n = 4, ref = 29663107),  # ATP2A2 encodes SERCA2, the ER Ca2+-ATPase whose dysregulation disrupts neuronal Ca2+ homeo...
  CACNB4 = list(n = 2, ref = 33904022),  # The calcium channel subunit CACNB4 is dysregulated as part of an ion-transport signature i...
  PJA2 = list(n = 2, ref = 32267716),  # The E3 ubiquitin ligase Praja2 (PJA2) regulates expression of AD genes APP, MAPT, and GSAP...
  PPP3R1 = list(n = "5+", ref = 34956428),  # PPP3R1, the regulatory subunit of the calcium-dependent phosphatase calcineurin, is downre...
  SLC24A2 = list(n = 1, ref = 28547530),  # NCKX2 (SLC24A2) protein/mRNA are reduced in CA1 of APP23 AD mice; NCKX2-heterozygous mice ...
  STIM2 = list(n = "5+", ref = 28087881),  # STIM2 senses ER calcium depletion and mediates store-operated calcium entry (SOCE) in neur...
  TMEM35A = list(n = 5, ref = 34446574),  # NACHO (TMEM35A) chaperones assembly of Ca2+-permeable α7 nicotinic receptors; Aβ-driven lo...
  VAPB = list(n = 4, ref = 38395965),  # VAPB-PTPIP51 ER-mitochondria tethering complexes regulate Ca2+ transfer and autophagy; dis...

  # AD genome-wide association (GWAS)
  ANKH = list(n = 3, ref = 39778705),  # ANKH lies in a locus enriched for protective alleles in AD-resistant centenarians and was ...
  ANKS1B = list(n = 3, ref = 41268768),  # A genome-wide significant AD-smoking interaction SNP near ANKS1B alters its expression in ...
  ARL6IP5 = list(n = 2, ref = 34654853),  # Deep post-GWAS analysis names ARL6IP5 as a putative AD risk gene showing altered network c...
  CDS2 = list(n = 1, ref = 39559883),  # Mendelian randomization integrating eQTL and AD GWAS data causally associated CDS2, a circ...
  CNOT7 = list(n = 2, ref = 33757599),  # A GWAS of cognitive resilience to brain amyloidosis identified a genome-wide-significant, ...
  CPNE4 = list(n = 1, ref = 23202439),  # A copy-number-variation genome-wide association study of age-at-onset in AD identified an ...
  EHBP1 = list(n = 1, ref = 35386118),  # A GWAS of AD-related quantitative endophenotypes found a genome-wide significant associati...
  EXOC4 = list(n = 1, ref = 23978990),  # Genome-wide homozygosity mapping in Caribbean Hispanics identified a recessive AD-associat...
  GSE1 = list(n = 1, ref = 41751570),  # Multi-tissue eQTL analysis identified GSE1 as the sole regulatory gene specific to early-o...
  LRP11 = list(n = 2, ref = 41460672),  # A proteome-wide association study identified genetically-regulated plasma LRP11 as a novel...
  NALCN = list(n = 3, ref = 33797837),  # Family-based whole-genome sequencing identified NALCN as a novel rare-variant AD risk locu...
  NRG3 = list(n = 3, ref = 24061483),  # NRG3 SNPs/haplotypes are associated with AD risk and age at onset in case-control and fami...
  PIK3R1 = list(n = 2, ref = 36530083),  # Genetic variants in PIK3R1 (neurotrophin signaling pathway) are significantly associated w...
  RORB = list(n = "5+", ref = 37734269),  # RORB is described as an AD genetic susceptibility gene and marks layer-specific excitatory...
  SETX = list(n = 2, ref = 24694197),  # Case-control study found SETX genetic variants/haplotypes significantly associated with AD...
  TNKS = list(n = 1, ref = 29885764),  # TNKS (tankyrase) carries a SNP significantly associated with AD-related increases in subco...

  # Prefilter database entries
  ADGRB3 = list(n = 1, ref = "platform.opentargets.org"),  # adhesion G protein-coupled receptor B3; AD-associated in OpenTargets_Platform
  ADK = list(n = 1, ref = "platform.opentargets.org"),  # adenosine kinase; AD-associated in OpenTargets_Platform
  ALG10 = list(n = 1, ref = "platform.opentargets.org"),  # ALG10 alpha-1,2-glucosyltransferase; AD-associated in OpenTargets_Platform
  ANK3 = list(n = 1, ref = "platform.opentargets.org"),  # ankyrin 3; AD-associated in OpenTargets_Platform
  ANKMY2 = list(n = 1, ref = "platform.opentargets.org"),  # ankyrin repeat and MYND domain containing 2; AD-associated in OpenTargets_Platform
  APPBP2 = list(n = 1, ref = "platform.opentargets.org"),  # amyloid beta precursor protein binding protein 2; AD-associated in OMIM
  B3GNT2 = list(n = 1, ref = "platform.opentargets.org"),  # UDP-GlcNAc:betaGal beta-1,3-N-acetylglucosaminyltransferase 2; AD-associated in OpenTargets_Platform
  BRWD1 = list(n = 1, ref = "platform.opentargets.org"),  # bromodomain and WD repeat domain containing 1; AD-associated in OpenTargets_Platform
  C9orf72 = list(n = 1, ref = "platform.opentargets.org"),  # C9orf72-SMCR8 complex subunit; AD-associated in OMIM
  CACNA1B = list(n = 1, ref = "platform.opentargets.org"),  # calcium voltage-gated channel subunit alpha1 B; AD-associated in OpenTargets_Platform
  CCNT2 = list(n = 1, ref = "platform.opentargets.org"),  # cyclin T2; AD-associated in OpenTargets_Platform
  CEP57 = list(n = 1, ref = "platform.opentargets.org"),  # centrosomal protein 57; AD-associated in OpenTargets_Platform
  CEP68 = list(n = 1, ref = "platform.opentargets.org"),  # centrosomal protein 68; AD-associated in OpenTargets_Platform
  CISD1 = list(n = 1, ref = "platform.opentargets.org"),  # CDGSH iron sulfur domain 1; AD-associated in OpenTargets_Platform
  CKAP5 = list(n = 1, ref = "platform.opentargets.org"),  # cytoskeleton associated protein 5; AD-associated in OpenTargets_Platform
  COG5 = list(n = 1, ref = "platform.opentargets.org"),  # component of oligomeric golgi complex 5; AD-associated in OpenTargets_Platform
  CRBN = list(n = 1, ref = "platform.opentargets.org"),  # cereblon; AD-associated in OpenTargets_Platform
  CSE1L = list(n = 1, ref = "platform.opentargets.org"),  # chromosome segregation 1 like; AD-associated in OpenTargets_Platform
  CSNK1G3 = list(n = 1, ref = "platform.opentargets.org"),  # casein kinase 1 gamma 3; AD-associated in OpenTargets_Platform
  CUL2 = list(n = 1, ref = "platform.opentargets.org"),  # cullin 2; AD-associated in OpenTargets_Platform
  CUL3 = list(n = 1, ref = "platform.opentargets.org"),  # cullin 3; AD-associated in OpenTargets_Platform
  CYRIB = list(n = 1, ref = "platform.opentargets.org"),  # CYFIP related Rac1 interactor B; AD-associated in OpenTargets_Platform
  DNM1L = list(n = 1, ref = "platform.opentargets.org"),  # dynamin 1 like; AD-associated in OMIM
  DOCK3 = list(n = 1, ref = "platform.opentargets.org"),  # dedicator of cytokinesis 3; AD-associated in OpenTargets_Platform
  EFL1 = list(n = 1, ref = "platform.opentargets.org"),  # elongation factor like GTPase 1; AD-associated in OpenTargets_Platform
  EIF2S1 = list(n = 1, ref = "platform.opentargets.org"),  # eukaryotic translation initiation factor 2 subunit alpha; AD-associated in OMIM
  ERCC8 = list(n = 1, ref = "platform.opentargets.org"),  # ERCC excision repair 8, CSA ubiquitin ligase complex subunit; AD-associated in OpenTargets_Platform
  FAR1 = list(n = 1, ref = "platform.opentargets.org"),  # fatty acyl-CoA reductase 1; AD-associated in OpenTargets_Platform
  FBXO11 = list(n = 1, ref = "platform.opentargets.org"),  # F-box protein 11; AD-associated in OpenTargets_Platform
  G3BP2 = list(n = 1, ref = "platform.opentargets.org"),  # G3BP stress granule assembly factor 2; AD-associated in OpenTargets_Platform
  GALNT13 = list(n = 1, ref = "platform.opentargets.org"),  # polypeptide N-acetylgalactosaminyltransferase 13; AD-associated in OpenTargets_Platform
  GAPVD1 = list(n = 1, ref = "platform.opentargets.org"),  # GTPase activating protein and VPS9 domains 1; AD-associated in OpenTargets_Platform
  GUCY1B1 = list(n = 1, ref = "platform.opentargets.org"),  # guanylate cyclase 1 soluble subunit beta 1; AD-associated in OpenTargets_Platform
  HELQ = list(n = 1, ref = "platform.opentargets.org"),  # helicase, POLQ like; AD-associated in OpenTargets_Platform
  HNRNPA0 = list(n = 1, ref = "platform.opentargets.org"),  # heterogeneous nuclear ribonucleoprotein A0; AD-associated in OpenTargets_Platform
  IARS2 = list(n = 1, ref = "platform.opentargets.org"),  # isoleucyl-tRNA synthetase 2, mitochondrial; AD-associated in OpenTargets_Platform
  IL1RAP = list(n = 1, ref = "platform.opentargets.org"),  # interleukin 1 receptor accessory protein; AD-associated in OpenTargets_Platform
  IPO11 = list(n = 1, ref = "platform.opentargets.org"),  # importin 11; AD-associated in OpenTargets_Platform
  JAZF1 = list(n = 1, ref = "platform.opentargets.org"),  # JAZF zinc finger 1; AD-associated in OpenTargets_Platform
  KIF21A = list(n = 1, ref = "platform.opentargets.org"),  # kinesin family member 21A; AD-associated in OpenTargets_Platform
  KLHL28 = list(n = 1, ref = "platform.opentargets.org"),  # kelch like family member 28; AD-associated in OpenTargets_Platform
  KLHL42 = list(n = 1, ref = "platform.opentargets.org"),  # kelch like family member 42; AD-associated in OpenTargets_Platform
  LTN1 = list(n = 1, ref = "platform.opentargets.org"),  # listerin E3 ubiquitin protein ligase 1; AD-associated in OpenTargets_Platform
  MADD = list(n = 1, ref = "platform.opentargets.org"),  # MAP kinase activating death domain; AD-associated in OpenTargets_Platform
  MAPK6 = list(n = 1, ref = "platform.opentargets.org"),  # mitogen-activated protein kinase 6; AD-associated in OpenTargets_Platform
  MDH1 = list(n = 1, ref = "platform.opentargets.org"),  # malate dehydrogenase 1; AD-associated in OpenTargets_Platform
  MKKS = list(n = 1, ref = "platform.opentargets.org"),  # MKKS centrosomal shuttling protein; AD-associated in OpenTargets_Platform
  MME = list(n = 1, ref = "platform.opentargets.org"),  # membrane metalloendopeptidase; AD-associated in OMIM
  MTMR2 = list(n = 1, ref = "platform.opentargets.org"),  # myotubularin related protein 2; AD-associated in OpenTargets_Platform
  MTOR = list(n = 1, ref = "platform.opentargets.org"),  # mechanistic target of rapamycin kinase; AD-associated in OpenTargets_Platform
  NCKAP1 = list(n = 1, ref = "platform.opentargets.org"),  # NCK associated protein 1; AD-associated in OMIM
  NDFIP2 = list(n = 1, ref = "platform.opentargets.org"),  # Nedd4 family interacting protein 2; AD-associated in OpenTargets_Platform
  NPTN = list(n = 1, ref = "platform.opentargets.org"),  # neuroplastin; AD-associated in OpenTargets_Platform
  NRIP1 = list(n = 1, ref = "platform.opentargets.org"),  # ; AD-associated in ClinVar
  NRXN1 = list(n = 1, ref = "platform.opentargets.org"),  # neurexin 1; AD-associated in OpenTargets_Platform
  PARG = list(n = 1, ref = "platform.opentargets.org"),  # poly(ADP-ribose) glycohydrolase; AD-associated in OMIM
  PTCD2 = list(n = 1, ref = "platform.opentargets.org"),  # pentatricopeptide repeat domain 2; AD-associated in OpenTargets_Platform
  PTPRN2 = list(n = 1, ref = "platform.opentargets.org"),  # protein tyrosine phosphatase receptor type N2; AD-associated in OpenTargets_Platform
  RAB18 = list(n = 1, ref = "platform.opentargets.org"),  # RAB18, member RAS oncogene family; AD-associated in OpenTargets_Platform
  RAB1A = list(n = 1, ref = "platform.opentargets.org"),  # RAB1A, member RAS oncogene family; AD-associated in OpenTargets_Platform
  RAPGEF2 = list(n = 1, ref = "platform.opentargets.org"),  # Rap guanine nucleotide exchange factor 2; AD-associated in OpenTargets_Platform
  RBM11 = list(n = 1, ref = "platform.opentargets.org"),  # ; AD-associated in ClinVar
  RIMS1 = list(n = 1, ref = "platform.opentargets.org"),  # regulating synaptic membrane exocytosis 1; AD-associated in OpenTargets_Platform
  RNF103 = list(n = 1, ref = "platform.opentargets.org"),  # ring finger protein 103; AD-associated in OMIM
  RNF11 = list(n = 1, ref = "platform.opentargets.org"),  # ring finger protein 11; AD-associated in OMIM
  RPL17 = list(n = 1, ref = "platform.opentargets.org"),  # ribosomal protein L17; AD-associated in OpenTargets_Platform
  RPL21 = list(n = 1, ref = "platform.opentargets.org"),  # ribosomal protein L21; AD-associated in OpenTargets_Platform
  RPS29 = list(n = 1, ref = "platform.opentargets.org"),  # ribosomal protein S29; AD-associated in OpenTargets_Platform
  SEMA6D = list(n = 1, ref = "platform.opentargets.org"),  # semaphorin 6D; AD-associated in OpenTargets_Platform
  SMARCA2 = list(n = 1, ref = "platform.opentargets.org"),  # SWI/SNF related BAF chromatin remodeling complex subunit ATPase 2; AD-associated in OpenTargets_Platform
  SV2A = list(n = 1, ref = "platform.opentargets.org"),  # synaptic vesicle glycoprotein 2A; AD-associated in OpenTargets_Platform
  TAX1BP1 = list(n = 1, ref = "platform.opentargets.org"),  # Tax1 binding protein 1; AD-associated in OpenTargets_Platform
  TBC1D15 = list(n = 1, ref = "platform.opentargets.org"),  # TBC1 domain family member 15; AD-associated in OpenTargets_Platform
  TBK1 = list(n = 1, ref = "platform.opentargets.org"),  # TANK binding kinase 1; AD-associated in OMIM
  TMEM106B = list(n = 1, ref = "platform.opentargets.org"),  # transmembrane protein 106B; AD-associated in OpenTargets_Platform
  TMEM126A = list(n = 1, ref = "platform.opentargets.org"),  # transmembrane protein 126A; AD-associated in OpenTargets_Platform
  TMEM132B = list(n = 1, ref = "platform.opentargets.org"),  # transmembrane protein 132B; AD-associated in OpenTargets_Platform
  TNFRSF21 = list(n = 1, ref = "platform.opentargets.org"),  # TNF receptor superfamily member 21; AD-associated in OpenTargets_Platform
  TOLLIP = list(n = 1, ref = "platform.opentargets.org"),  # toll interacting protein; AD-associated in OpenTargets_Platform
  TRIM36 = list(n = 1, ref = "platform.opentargets.org"),  # tripartite motif containing 36; AD-associated in OpenTargets_Platform
  TRUB1 = list(n = 1, ref = "platform.opentargets.org"),  # TruB pseudouridine synthase family member 1; AD-associated in OpenTargets_Platform
  TUBA1B = list(n = 1, ref = "platform.opentargets.org"),  # tubulin alpha 1b; AD-associated in OpenTargets_Platform
  TUBA4A = list(n = 1, ref = "platform.opentargets.org"),  # tubulin alpha 4a; AD-associated in OMIM; OpenTargets_Platform
  TUBB = list(n = 1, ref = "platform.opentargets.org"),  # tubulin beta class I; AD-associated in OpenTargets_Platform
  TUBB2A = list(n = 1, ref = "platform.opentargets.org"),  # tubulin beta 2A class IIa; AD-associated in OpenTargets_Platform
  TUBB3 = list(n = 1, ref = "platform.opentargets.org"),  # tubulin beta 3 class III; AD-associated in OpenTargets_Platform
  TUBB4B = list(n = 1, ref = "platform.opentargets.org"),  # tubulin beta 4B class IVb; AD-associated in OpenTargets_Platform
  USP44 = list(n = 1, ref = "platform.opentargets.org"),  # ubiquitin specific peptidase 44; AD-associated in OpenTargets_Platform
  VCPIP1 = list(n = 1, ref = "platform.opentargets.org"),  # valosin containing protein interacting protein 1; AD-associated in OpenTargets_Platform
  VPS13C = list(n = 1, ref = "platform.opentargets.org"),  # vacuolar protein sorting 13 homolog C; AD-associated in OpenTargets_Platform
  VPS35 = list(n = 1, ref = "platform.opentargets.org"),  # VPS35 retromer complex component; AD-associated in OpenTargets_Platform
  VSNL1 = list(n = 1, ref = "platform.opentargets.org"),  # visinin like 1; AD-associated in OMIM
  VWA8 = list(n = 1, ref = "platform.opentargets.org"),  # von Willebrand factor A domain containing 8; AD-associated in OpenTargets_Platform
  ZBTB24 = list(n = 1, ref = "platform.opentargets.org"),  # zinc finger and BTB domain containing 24; AD-associated in OpenTargets_Platform
  ZNF287 = list(n = 1, ref = "platform.opentargets.org"),  # zinc finger protein 287; AD-associated in OpenTargets_Platform
  ZNF33B = list(n = 1, ref = "platform.opentargets.org")  # zinc finger protein 33B; AD-associated in OpenTargets_Platform
)
