library(qs)
library(data.table)
library(DESeq2)
library(edgeR)
library(tidyverse)
library(future.apply)
library(BiocParallel)
options(future.globals.maxSize = 3000 * 1024^2)

# ============================================================
# RUN FLAGS — set to FALSE to skip any combination
# ============================================================
RUN_MIT    <- TRUE
RUN_SEA    <- TRUE
RUN_EDGER  <- TRUE
RUN_DESEQ2 <- TRUE
RUN_DFC    <- TRUE
RUN_MTG    <- TRUE

# Set to NULL to disable gene filtering and use the full gene universe.
GENE_FILTER_PATH <- file.path(Sys.getenv("REPO_DIR", "/home/gugene/code/git/kang-oldham-2026"), "figures/fig_7/all_bulk_genes.txt")

# ============================================================
# PLACEHOLDERS — paths and column names
# ============================================================

# MIT pseudobulk data: generated by prepare_mit_multiome_and_pseudobulk.py
# using Gabitto_metacell_labels for celltype definitions.
# Pathology column contains: earlyAD, lateAD, nonAD — mapped to AD/Con below.
MIT_BASE_DIR     <- file.path(Sys.getenv("REPO_DIR", "/home/gugene/code/git/kang-oldham-2026"), "figures/fig_7/mit_pseudobulk")
MIT_CELLTYPE_COL <- "Gabitto_metacell_labels"
MIT_DX_COL       <- "Diagnosis"    # column in pseudobulk annotations
MIT_DX_CONTROL   <- "Con"
MIT_DX_AD        <- "AD"

# SEA-AD pseudobulk data (already pseudobulked)
SEA_DX_COL     <- "Dx"
SEA_DX_CONTROL <- "Control"
SEA_DX_AD      <- "Alzheimers"
SEA_CELLTYPE_COL <- "Subclass"

# Per-region paths
REGION_CONFIG <- list(

  DFC = list(
    mit_pb_expr = file.path(MIT_BASE_DIR, "mit_pfc_pseudobulk.csv.gz"),
    mit_pb_anno = file.path(MIT_BASE_DIR, "mit_pfc_pseudobulk_annotations.csv"),
    sea_expr    = file.path(Sys.getenv("DATA_DIR", "/mnt/bdata/gugene"), "datasets/SN_RNAseq/sea_ad_2024/RNAseq/dfc_data_pseudobulk/sea_dfc_pseudobulk.csv.gz"),
    sea_anno    = file.path(Sys.getenv("DATA_DIR", "/mnt/bdata/gugene"), "datasets/SN_RNAseq/sea_ad_2024/RNAseq/dfc_data_pseudobulk/sea_dfc_pseudobulk_annotations.csv"),
    mit_de_dir  = file.path(Sys.getenv("REPO_DIR", "/home/gugene/code/git/kang-oldham-2026"), "figures/fig_7/DE_ADvsCon/MIT_DE_results_DFC"),
    sea_de_dir  = file.path(Sys.getenv("REPO_DIR", "/home/gugene/code/git/kang-oldham-2026"), "figures/fig_7/DE_ADvsCon/SEA_DE_results_DFC"),
    mit_prefix  = "mit_dfc_",
    sea_prefix  = "sea_dfc_"
  ),

  MTG = list(
    mit_pb_expr = file.path(MIT_BASE_DIR, "mit_mtc_pseudobulk.csv.gz"),
    mit_pb_anno = file.path(MIT_BASE_DIR, "mit_mtc_pseudobulk_annotations.csv"),
    sea_expr    = file.path(Sys.getenv("DATA_DIR", "/mnt/bdata/gugene"), "datasets/SN_RNAseq/sea_ad_2024/mtg/RNAseq/mtg_data_pseudobulk/sea_mtg_pseudobulk.csv.gz"),
    sea_anno    = file.path(Sys.getenv("DATA_DIR", "/mnt/bdata/gugene"), "datasets/SN_RNAseq/sea_ad_2024/mtg/RNAseq/mtg_data_pseudobulk/sea_mtg_pseudobulk_annotations.csv"),
    mit_de_dir  = file.path(Sys.getenv("REPO_DIR", "/home/gugene/code/git/kang-oldham-2026"), "figures/fig_7/DE_ADvsCon/MIT_DE_results_MTG"),
    sea_de_dir  = file.path(Sys.getenv("REPO_DIR", "/home/gugene/code/git/kang-oldham-2026"), "figures/fig_7/DE_ADvsCon/SEA_DE_results_MTG"),
    mit_prefix  = "mit_mtg_",
    sea_prefix  = "sea_mtg_"
  )

)

# ============================================================
# Parallelism setup
# ============================================================
N_WORKERS      <- min(parallelly::availableCores() - 1L, 8L)
plan(multisession, workers = N_WORKERS)
BPPARAM_SERIAL <- BiocParallel::SerialParam()


# ============================================================
# DE functions
# ============================================================

run_edger_dx_de <- function(rawcounts_df,   # data.frame: col1 = Gene, rest = samples
                             anno,           # data.frame: one row per sample
                             celltype_col,
                             dx_col,
                             dx_control,
                             dx_ad,
                             de_save_dir,
                             save_prefix = "") {

  if (!dir.exists(de_save_dir)) dir.create(de_save_dir, recursive = TRUE)

  genes_vec  <- rawcounts_df[, 1]
  counts_mat <- as.matrix(rawcounts_df[, -1])

  cts <- unique(anno[[celltype_col]])
  result_list <- future_lapply(cts, function(ct) {

    these      <- which(anno[[celltype_col]] == ct)
    sub_counts <- counts_mat[, these]
    sub_anno   <- anno[these, ]
    dx_fac     <- factor(sub_anno[[dx_col]], levels = c(dx_control, dx_ad))

    if (sum(dx_fac == dx_control) < 3 || sum(dx_fac == dx_ad) < 3) {
      message("  Skipping ", ct, ": fewer than 3 samples in one group")
      return(NULL)
    }

    keep       <- filterByExpr(sub_counts, group = dx_fac,
                               min.count = 5, min.total.count = 10)
    sub_counts <- sub_counts[keep, ]
    sub_genes  <- genes_vec[keep]

    design <- model.matrix(~ dx_fac)

    y   <- DGEList(counts = sub_counts, genes = sub_genes)
    y   <- calcNormFactors(y, method = "TMM")
    y   <- estimateDisp(y, design, robust = TRUE)
    fit <- glmFit(y, design)
    lrt <- glmLRT(fit, coef = 2)

    res <- as.data.frame(topTags(lrt, n = nrow(sub_counts)))
    res$celltype <- ct
    res

  }, future.seed = TRUE)

  names(result_list) <- cts
  result_list <- Filter(Negate(is.null), result_list)

  saveRDS(result_list,
          file = file.path(de_save_dir, paste0(save_prefix, "edgeR_ADvsCon_by_celltype.RDS")))
  message(save_prefix, "edgeR DE done")
  invisible(result_list)
}


run_deseq2_dx_de <- function(counts_mat,    # matrix or data.frame (genes x samples)
                              anno,
                              celltype_col,
                              dx_col,
                              dx_control,
                              dx_ad,
                              de_save_dir,
                              save_prefix = "") {

  if (!dir.exists(de_save_dir)) dir.create(de_save_dir, recursive = TRUE)

  if (is.data.frame(counts_mat)) {
    rn         <- counts_mat[, 1]
    counts_mat <- as.matrix(counts_mat[, -1])
    counts_mat <- round(counts_mat)
    storage.mode(counts_mat) <- "integer"
    rownames(counts_mat) <- rn
  } else {
    counts_mat <- round(counts_mat)
    storage.mode(counts_mat) <- "integer"
  }

  cts <- unique(anno[[celltype_col]])
  result_list <- future_lapply(cts, function(ct) {

    these      <- which(anno[[celltype_col]] == ct)
    sub_counts <- counts_mat[, these]
    sub_anno   <- anno[these, ]
    sub_anno$Dx <- factor(sub_anno[[dx_col]], levels = c(dx_control, dx_ad))

    if (sum(sub_anno$Dx == dx_control) < 3 || sum(sub_anno$Dx == dx_ad) < 3) {
      message("  Skipping ", ct, ": fewer than 3 samples in one group")
      return(NULL)
    }

    keep       <- rowSums(sub_counts >= 5) >= max(2, floor(ncol(sub_counts) * 0.2))
    sub_counts <- sub_counts[keep, ]

    dds  <- DESeqDataSetFromMatrix(
      countData = sub_counts,
      colData   = sub_anno,
      design    = ~ Dx
    )
    dds1 <- DESeq(dds,
                  test    = "LRT",
                  reduced = ~ 1,
                  BPPARAM = BPPARAM_SERIAL,
                  quiet   = TRUE)

    res_name <- paste0("Dx_", dx_ad, "_vs_", dx_control)
    res   <- results(dds1, name = res_name)
    resdf <- as.data.frame(res@listData) |>
      `rownames<-`(res@rownames) |>
      arrange(padj)
    resdf$celltype <- ct
    resdf$genes    <- rownames(resdf)
    colnames(resdf)[c(2, 5, 6)] <- c("logFC", "PValue", "FDR")
    resdf

  }, future.seed = TRUE)

  names(result_list) <- cts
  result_list <- Filter(Negate(is.null), result_list)

  qsave(result_list,
        file = file.path(de_save_dir, paste0(save_prefix, "DESeq2_ADvsCon_by_celltype.qs")))
  message(save_prefix, "DESeq2 DE done")
  invisible(result_list)
}


# ============================================================
# Gene filter (optional)
# ============================================================
if (!is.null(GENE_FILTER_PATH)) {
  gene_filter <- readLines(GENE_FILTER_PATH)
  gene_filter <- gene_filter[nzchar(trimws(gene_filter))]
  message("Gene filter loaded: ", length(gene_filter), " genes from ", GENE_FILTER_PATH)
} else {
  gene_filter <- NULL
}

# ============================================================
# Main loop: iterate over regions
# ============================================================
regions_to_run <- names(REGION_CONFIG)[c(RUN_DFC, RUN_MTG)]

for (region in regions_to_run) {
  cfg <- REGION_CONFIG[[region]]
  message("\n========== ", region, " ==========")

  # ---- Load both datasets (always — gene intersection is always enforced) ----
  message("--- Loading MIT pseudobulk (", region, ") ---")

  mit_rawcounts <- fread(cfg$mit_pb_expr, data.table = FALSE) |>
    tibble::column_to_rownames(var = "Gene")

  mit_anno_pb <- fread(cfg$mit_pb_anno, data.table = FALSE) |>
    dplyr::mutate(
      Dx = factor(dplyr::case_when(
        .data[[MIT_DX_COL]] %in% c("earlyAD", "lateAD") ~ MIT_DX_AD,
        .data[[MIT_DX_COL]] == "nonAD"                  ~ MIT_DX_CONTROL,
        TRUE                                             ~ NA_character_
      ), levels = c(MIT_DX_CONTROL, MIT_DX_AD)),
      celltype = factor(.data[[MIT_CELLTYPE_COL]])
    )

  mit_rawcounts <- data.frame(Gene = rownames(mit_rawcounts), mit_rawcounts)
  message("MIT loaded: ", nrow(mit_anno_pb), " pseudobulk samples, ",
          length(unique(mit_anno_pb$celltype)), " celltypes")

  message("--- Loading SEA-AD (", region, ") ---")

  sea_rawcounts <- fread(cfg$sea_expr, data.table = FALSE) |>
    tibble::column_to_rownames(var = "Gene") |>
    as.matrix() |>
    round() |>
    (\(x) { storage.mode(x) <- "integer"; x })()

  sea_anno_pb <- fread(cfg$sea_anno, data.table = FALSE) |>
    dplyr::mutate(
      Dx       = factor(.data[[SEA_DX_COL]], levels = c(SEA_DX_CONTROL, SEA_DX_AD)),
      celltype = factor(.data[[SEA_CELLTYPE_COL]])
    )

  # ---- Align gene universes (always enforced) ----
  common_genes <- intersect(mit_rawcounts$Gene, rownames(sea_rawcounts))
  if (!is.null(gene_filter)) {
    n_before     <- length(common_genes)
    common_genes <- intersect(common_genes, gene_filter)
    message(length(common_genes), " genes after intersecting with gene filter ",
            "(", n_before - length(common_genes), " dropped)")
  } else {
    message(length(common_genes), " genes in common between datasets")
  }
  mit_rawcounts_mat <- mit_rawcounts[mit_rawcounts$Gene %in% common_genes, ]
  sea_rawcounts_mat <- data.frame(Gene = rownames(sea_rawcounts),
                                  sea_rawcounts)[rownames(sea_rawcounts) %in% common_genes, ]

  # ---- edgeR ----
  if (RUN_EDGER) {
    if (RUN_MIT) {
      message("--- edgeR: MIT (", region, ") ---")
      run_edger_dx_de(
        rawcounts_df = mit_rawcounts_mat,
        anno         = mit_anno_pb,
        celltype_col = "celltype",
        dx_col       = "Dx",
        dx_control   = MIT_DX_CONTROL,
        dx_ad        = MIT_DX_AD,
        de_save_dir  = cfg$mit_de_dir,
        save_prefix  = cfg$mit_prefix
      )
    }
    if (RUN_SEA) {
      message("--- edgeR: SEA-AD (", region, ") ---")
      run_edger_dx_de(
        rawcounts_df = sea_rawcounts_mat,
        anno         = sea_anno_pb,
        celltype_col = "celltype",
        dx_col       = "Dx",
        dx_control   = SEA_DX_CONTROL,
        dx_ad        = SEA_DX_AD,
        de_save_dir  = cfg$sea_de_dir,
        save_prefix  = cfg$sea_prefix
      )
    }
  }

  # ---- DESeq2 ----
  if (RUN_DESEQ2) {
    if (RUN_MIT) {
      message("--- DESeq2: MIT (", region, ") ---")
      run_deseq2_dx_de(
        counts_mat   = mit_rawcounts_mat,
        anno         = mit_anno_pb,
        celltype_col = "celltype",
        dx_col       = "Dx",
        dx_control   = MIT_DX_CONTROL,
        dx_ad        = MIT_DX_AD,
        de_save_dir  = cfg$mit_de_dir,
        save_prefix  = cfg$mit_prefix
      )
    }
    if (RUN_SEA) {
      message("--- DESeq2: SEA-AD (", region, ") ---")
      run_deseq2_dx_de(
        counts_mat   = sea_rawcounts_mat,
        anno         = sea_anno_pb,
        celltype_col = "celltype",
        dx_col       = "Dx",
        dx_control   = SEA_DX_CONTROL,
        dx_ad        = SEA_DX_AD,
        de_save_dir  = cfg$sea_de_dir,
        save_prefix  = cfg$sea_prefix
      )
    }
  }
}

message("\n--- All DE complete ---")
